<?php
/**
 * Language labels for plugin "tx_jwcalendar_pi1"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'inputDate' => '###month### / ###day### / ###year### at ###hour### : ###minute###',
		'outputDate' => '###date### at ###time###',
		'outputDateEnd' => '###date### at ###time###',
		'dayViewTitle' => 'Day View',
		'upcomingEventsTitle' => 'Upcoming Events',
		'singleEventTitle' => 'Event Info',
		'feEntryFormTitle' => 'Event Submission',
		'oneDayTitle' => 'Event info',
		'weekViewTitle' => 'Week View', 
		'MONTH'	=> 'Month view',
		'LIST'	=> 'List view',
		'WEEK'	=> 'Week view',
		'DAY'	=> 'Day view',
		'feEntryPrevEventsTitle' => 'Previous event submissions',
		'readMoreLinkLabel' => 'More...',
		'feEntrySubmitEventButtonLabel' => '[Event submission by Guests]',
		'feEntryEditEventButtonLabel' => 'Event submission rework by Guests',
		'OrganizerTitle' => 'Organizer',
		'LocationTitle' => 'Location',	
		'backButtonLabel' => 'Back',
		'backTo' =>	'back to ', 
		'previewButtonLabel' => 'Preview',
		'saveButtonLabel' => 'Save',
		'editButtonLabel' => 'Edit',
		'deleteButtonLabel' => 'Delete',
		'yesButtonLabel' => 'Yes',
		'noButtonLabel' => 'No',
		'organiserLabel' => 'Organiser',
		'locationLabel' => 'Location',
		'beginLabel' => 'Begin',
		'endLabel' => 'End',
		'categoryLabel' => 'Category',
		'titleLabel' => 'Title',
		'teaserLabel' => 'Teaser',
		'descriptionLabel' => 'Description',
		'imageLabel' => 'Image',
		'linkLabel' => 'Link',
		'homepageLabel' => 'Homepage',
		'emailLabel' => 'Email',
 		'addressLabel' => 'Address',
		'phoneLabel' => 'Phone',
        'prev_events' => 'Previous Events',
        'next_events' => 'Next Events',
        'day_prev' => '<<',
        'day_next' => '>>',
        'week_prev' => '<<',
        'week_next' => '>>',
        'no_prev_events' => ' ',
        'no_next_events' => ' ',
		'titleMonthView' => 'Month View',
		'allCategories' => 	'All',
		'week' => '. week',
		'ConfirmDeleteMessage' => 'Really delete this Event submission?',	
		'thxForEntryMessage' => 'Thank you for contribution.',
		'beginDayError' => 'Beginning: Invalid day.',
		'beginTimeError' => 'Beginning: Invalid time.',
		'endDayError' => 'End: Invalid day.',
		'endTimeError' => 'End: Invalid time.',
		'timeOrderError' => 'The event can\'t end before its beginning.',
		'emptyTitleError' => 'Missing title.',
		'emptyDescriptionError' => 'Missing description',
		'emptyLocationError' => 'Missing location.',
		'emptyOrganiserError' => 'Misseng organiser.',
		'emailFormatError' => 'Wrong email format.',
		'dbError' => 'Database error, no event entry!',
		'FileExistError'  => 'The file already exists.',
		'FileMaxSizeError' => 'The file is too big.',
		'FileMimeError' => 'This mime type is not allowed.',
		'FileExtensionError' => 'This file extension is not allowed.',
	),
	'dk' => Array (
	),
	'de' => Array (
		'inputDate' => '###day### . ###month### . ###year### um ###hour### : ###minute### Uhr',
		'outputDate' => '###date### um ###time### Uhr',
		'dayViewTitle' => 'Tagesansicht',
		'upcomingEventsTitle' => 'Übersicht',
		'singleEventTitle' => 'Kategorie',
		'oneDayTitle' => 'Tagesansicht',
		'titleMonthView' => 'Übersicht', 
		'weekViewTitle' => 'Wochenansicht', 
		'MONTH'	=> 'Monatsansicht',
		'LIST'	=> 'Listenansicht',
		'WEEK'	=> 'Wochenansicht',
		'DAY'	=> 'Tagesansicht',
		'feEntryFormTitle' => 'Termin eintragen',
		'feEntryPrevEventsTitle' => 'Vorherige Termineinträge',
		'OrganizerTitle' => 'Veranstalter',
		'LocationTitle' => 'Veranstaltungort',	
		'readMoreLinkLabel' => 'Mehr ...', 
		'feEntrySubmitEventButtonLabel' => 'Termin eintragen',
		'feEntryEditEventButtonLabel' => 'Termin ändern',
		'backButtonLabel' => 'Zurück', 
		'backTo'=>	'Zurück zur ', 
		'previewButtonLabel' => 'Vorschau',
		'saveButtonLabel' => 'Eintragen',
		'editButtonLabel' => 'Bearbeiten',
		'deleteButtonLabel' => 'Entfernen',
		'yesButtonLabel' => 'Ja',
		'noButtonLabel' => 'Nein',
		'organiserLabel' => 'Veranstalter', 
		'locationLabel' => 'Veranstaltungsort',
		'beginLabel' => 'Anfang', 
		'endLabel' => 'Ende', 
		'categoryLabel' => 'Kategorie',
		'titleLabel' => 'Veranstaltungstitel', 
		'teaserLabel' => 'Teaser',
		'descriptionLabel' => 'Beschreibung', 
		'imageLabel' => 'Bild',
		'linkLabel' => 'Link',
		'homepageLabel' => 'Homepage',
		'emailLabel' => 'E-mail',
		'phoneLabel' => 'Telefon',
 		'addressLabel' => 'Anschrift',
        'prev_events' => 'vorige Termine',
        'no_prev_events' => ' ',
        'next_events' => 'weitere Termine',
        'no_next_events' => ' ',
        'day_prev' => '<<',
        'day_next' => '>>',
        'week_prev' => '<<',
        'week_next' => '>>',
		'allCategories' => 	'Please Select Category',
		'week' => '. Woche', 
		'ConfirmDeleteMessage' => 'Wollen sie diesen Eintrag wirklich entfernen?',	
		'thxForEntryMessage' => 'Vielen Dank für Ihren Eintrag',
		'beginDayError' => 'Anfang: Ungültiger Tag', 
		'beginTimeError' => 'Anfang: Ungültige Uhrzeit',
		'endDayError' => 'Ende: Ungültiger Tag',
		'endTimeError' => 'Ende: Ungültige Uhrzeit',
		'timeOrderError' => 'Das Ende kann nicht vor dem Beginn liegen.',
		'emptyTitleError' => 'Bitte Titel angeben',
		'emptyDescriptionError' => 'Bitte Beschreibung angeben', 
		'emptyLocationError' => 'Bitte Veranstaltungsort angeben', 
		'emptyOrganiserError' => 'Bitte Veranstalter angeben', 
		'emailFormatError' => 'Ungültiges Emailformat',
		'dbError' => 'Datenbankfehler: Leider kein Eintrag möglich', 
		'FileExistError'  => 'Die angegebene Datei existiert bereits.',
		'FileMaxSizeError' => 'Die angegebene Datei ist zu gross.',
		'FileMimeError' => 'Dieser mime-Typ ist nicht erlaubt.',
		'FileExtensionError' => 'Diese Dateiendung ist nicht erlaubt.',
			
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
		'inputDate' => '###day### . ###month### . ###year### a las ###hour### : ###minute###',
		'outputDate' => '###date### a las ###time###',
		'upcomingEventsTitle' => 'programa del evento',
		'singleEventTitle' => 'evento, actividad',
		'oneDayTitle' => 'Event info',
		'MONTH'	=> 'Month view',
		'LIST'	=> 'List view',
		'feEntryFormTitle' => 'inclusión del evento en la agenda',
		'readMoreLinkLabel' => 'más información',
		'feEntrySubmitEventButtonLabel' => 'inclusión del evento',
		'feEntryEditEventButtonLabel' => 'Event submission rework by Guests',
		'feEntryPrevEventsTitle' => 'Previous event submissions',
		'backButtonLabel' => 'retorno',
		'previewButtonLabel' => 'vista previa',
		'saveButtonLabel' => 'grabar',
		'editButtonLabel' => 'Edit',
		'deleteButtonLabel' => 'Delete',
		'yesButtonLabel' => 'Yes',
		'noButtonLabel' => 'No',
		'organiserLabel' => 'organizador',
		'locationLabel' => 'lugar del evento',
		'beginLabel' => 'inicio',
		'endLabel' => 'final',
		'categoryLabel' => 'Category',
		'titleLabel' => 'nombre del evento',
		'teaserLabel' => 'cabeceras',
		'descriptionLabel' => 'descripción',
		'imageLabel' => 'Image',
		'linkLabel' => 'link', 
		'homepageLabel' => 'Homepage',
		'emailLabel' => 'e-mail',
        'prev_events' => 'fechas previas',
        'no_prev_events' => ' ',
        'next_events' => 'próximas fechas',
        'no_next_events' => ' ',
		'titleMonthView' => 'programa del evento', 
		'allCategories' => 	'All',
		'week' => 'Semana',
		'ConfirmDeleteMessage' => 'Really delete this Event submission?',	
		'thxForEntryMessage' => 'muchas gracias por su inscripción',
		'beginDayError' => 'Inicio: falta la fecha',
		'beginTimeError' => 'Inicio: falta la hora',
		'endDayError' => 'Final: falta la fecha',
		'endTimeError' => 'Final: falta la hora',
		'timeOrderError' => 'El final no puede figurar antes que el inicio',
		'emptyTitleError' => 'Indicar el título',
		'emptyDescriptionError' => 'Hacer una descripción',
		'emptyLocationError' => 'Lugar en donde se realizará la actividad',
		'emptyOrganiserError' => 'Indicar el nombre del organizador',
		'emailFormatError' => 'Error en la dirección de e-mail',
		'dbError' => 'Error en el bando de datos',
		'FileExistError'  => 'The file already exists.',
		'FileMaxSizeError' => 'The file is too big.',
		'FileMimeError' => 'This mime type is not allowed.',
		'FileExtensionError' => 'This file extension is not allowed.',
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'inputDate' => '###month## / ###day### / ###year### kello ###hour### : ###minute###',
		'outputDate' => '###date### kello ###time###',
		'upcomingEventsTitle' => 'Tulevat tapahtumat',
		'singleEventTitle' => 'Tapahtumatiedot',
		'oneDayTitle' => 'Event info',
		'feEntryFormTitle' => 'Tapahtumailmoitus',
		'MONTH'	=> 'Month view',
		'LIST'	=> 'List view',
		'readMoreLinkLabel' => 'lue lisää &gt;&gt;',
		'feEntrySubmitEventButtonLabel' => '[Tapahtumailmoitus vierailijalta]',
		'feEntryEditEventButtonLabel' => 'Event submission rework by Guests',
		'feEntryPrevEventsTitle' => 'Previous event submissions',
		'backButtonLabel' => 'Takaisin',
		'previewButtonLabel' => 'Edellinen',
		'saveButtonLabel' => 'Tallenna',
		'editButtonLabel' => 'Edit',
		'deleteButtonLabel' => 'Delete',
		'yesButtonLabel' => 'Yes',
		'noButtonLabel' => 'No',
		'organiserLabel' => 'Järjestäjä',
		'locationLabel' => 'Paikka',
		'beginLabel' => 'Alkaa',
		'endLabel' => 'Päättyy',
		'titleLabel' => 'Otsikko',
		'teaserLabel' => 'Huokutin',
		'descriptionLabel' => 'Kuvaus',
		'linkLabel' => 'Linkki',
		'emailLabel' => 'Sähköpostiosoite',
		'ConfirmDeleteMessage' => 'Really delete this Event submission?',	
		'thxForEntryMessage' => 'Kiitos toiminnastasi.',
		'beginDayError' => 'Aloitus: virheellinen päiväys',
		'beginTimeError' => 'Aloitus: virheellinen aika',
		'endDayError' => 'Loppu: virheellinen päiväys',
		'endTimeError' => 'Loppu: virheellinen aika',
		'timeOrderError' => 'Tapahtuma ei voi loppua ennenkuin seon alkanut',
		'emptyTitleError' => 'Puuttuva otsikko ...',
		'emptyDescriptionError' => 'Puuttuva kuvaus ...',
		'emptyLocationError' => 'Puuttuva paikka ...',
		'emptyOrganiserError' => 'Puuttuva järjestäjä ...',
		'emailFormatError' => 'Virheellinen sähköpostiosoitteen muoto ...',
		'titleMonthView' => 'Tapahtuma selvitys',
		'week' => 'viikko',
		'dbError' => 'Database error',

	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'inputDate' => '###DAY### / ###MONTH### / ###YEAR### às ###HOUR### : ###MINUTE###',
		'outputDate' => '###DATE### às ###TIME###',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
);
?>
