<?php
/**
 * Language labels for module "tools_txchcforumM1"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'msg_forum_select' => 'Please select the forum you would like to administer:',
		'msg_selection_select' => 'Please select an option from the drop-down menu',
		'title' => 'CHC Forum Administration',
		'ad_cats' => 'Manage Categories',
		'ad_confs' => 'Manage Conferences',
		'ad_fgroups' => 'Manage Forum Groups',
		'f_conf' => 'Configure Forum',
		'addcat' => 'Add Category',
		'modcat' => 'Modify Category',
		'delcat' => 'Delete Category',
		'addconf' => 'Add Conference',
		'modconf' => 'Modify Conference',
		'delconf' => 'Delete Conference',
		'addfgrp' => 'Add Forum-group',
		'modfgrp' => 'Modify Forum-group',
		'delfgrp' => 'Delete Forum-group',
		'message_posts_del' => 'The following POSTS (uid / subject) were permanently deleted because they were missing a parent conference and/or thread:',
		'message_posts_prune_del' => 'The following POSTS (uid / subject) were permanently deleted because they exceeded the pruning age:',
		'message_threads_del' => 'The following THREADS (uid / subject) were permanently deleted because they were either missing a parent conference or because they contained no posts:',
		'message_del' => 'The DB cleaner scanned all the chc_forum tables, and deleted all records where deleted = 1. In total, it deleted the following number of records:',
		'message_del_lbl' => 'Deleted Posts:',
		'message_pr_del' => 'The DB cleaner also cleaned up the posts_read table, which keeps track of which posts each user has read. Any entries for which a coresponding post no longer exists were deleted.',
		'message_none' => 'None!',
		'message_add_success' => 'Record successfully added!',
		'message_del_success' => 'Record successfully deleted!',
		'message_mod_success' => 'Record successfully modified!',
		'message_fconf_success' => 'Your changes to the forum configuration have been saved!',
		'mailer_forum_url_lbl' => 'Enter the URL for your site. Don\'t forget the final slash!<br /><br />Example: http://yourdomain.com/',
		'mailer_disable_lbl' => 'Check this box to disable the mailing list features.',
		'tmpl_path_lbl' => 'Path to custom forum templates:<br /><br />This should be a relative path from the root of your typo3 installation. Leave this blank to use the default forum templates.<br /><br />Example: fileadmin/forum_templates/',
		'allowed_file_types_lbl' => 'Comma seperated list of allowed attachment file types<br /><br />WARNING: Do not allow php or html files as attachments. Doing so poses a grave security risk since all files that are attached can potentially be executed from a browser.<br /><br />Example: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'Comma seperated list of allowed mime types for attachments.<br /><br />Example: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Max user picture upload size (in kb)',
		'max_attach_lbl' => 'Max attachment size (in kb)',
		'usrsAD_lbl' => 'Users A-D',
		'usrsEH_lbl' => 'Users E-H',
		'usrsIL_lbl' => 'Users I-L',
		'usrsMP_lbl' => 'Users M-P',
		'usrsQT_lbl' => 'Users Q-T',
		'usrsUZ_lbl' => 'Users U-Z',
		'add_fgrp' => 'Add a forum-group',
		'del_fgrp' => 'Delete a forum-group',
		'mod_fgrp' => 'Modify a forum-group',
		'add_conf' => 'Add a conference',
		'del_conf' => 'Delete a conference',
		'mod_conf' => 'Modify a conference',
		'add_cat' => 'Add a category',
		'del_cat' => 'Delete a category',
		'mod_cat' => 'Modify a category',
		'cat_title_hdr' => 'Please enter a title (required):',
		'cat_title_lbl' => 'Title:',
		'cat_hide_lbl' => 'Hide:',
		'cat_grps_lbl' => 'Frontend group that can access this category and its child conferences:',
		'cat_desc_lbl' => 'Category Description:',
		'cat_hide_hdr' => 'Check to hide this category:',
		'cat_desc_hdr' => 'Enter a description for this category:',
		'cat_grps_hdr' => 'Category Access (optional):',
		'cat_fgaccess_lbl' => 'Forum-groups that can access this category and its child conferences:',
		'cnf_hide_hdr' => 'Hide:',
		'cnf_cat_hdr' => 'Select the category that this conference belongs to:',
		'cnf_title_hdr' => 'Enter the name of this conference:',
		'cnf_desc_hdr' => 'Enter a description for this conference:',
		'cnf_publ_r_hdr' => 'Check this box to grant read access to anonymous users:',
		'cnf_publ_w_hdr' => 'Check this box to grant post access to anonymous users:',
		'cnf_fgaccess_hdr' => 'Forum-groups that can access this conference:',
		'cnf_fgattach_hdr' => 'Forum-groups that may attach files to posts:',
		'cnf_usrs_hdr' => 'Users assigned to moderate this conference:',
		'cnf_hide_lbl' => 'Check to hide this conference:',
		'cnf_cat_lbl' => 'Category',
		'cnf_title_lbl' => 'Conference Name',
		'cnf_desc_lbl' => 'Conference description',
		'cnf_publ_r_lbl' => 'Anonymous Read Access<br />[If you check this, guest (not logged in) users  will be able to read messages in this conference.]',
		'cnf_publ_w_lbl' => 'Anonymous Post Access<br />[If you check this, guest (not logged in) users will be able to post new messages in this conference.]',
		'cnf_fgaccess_lbl' => 'Forum-group read / post access',
		'cnf_fgattach_lbl' => 'Forum-group attach access',
		'cnf_user_edit_hdr' => 'Post editing:',
		'cnf_user_edit_lbl' => 'Allow users to edit their own posts?',
		'fgrp_hide_lbl' => 'Hide:',
		'fgrp_title_lbl' => 'Title:',
		'fgrp_desc_lbl' => 'Forum Group Description:',
		'fgrp_grps_lbl' => 'Frontend Groups:',
		'fgrp_hide_hdr' => 'Check to hide this group:',
		'fgrp_title_hdr' => 'Please enter a title (required):',
		'fgrp_desc_hdr' => 'Enter a description for this group:',
		'fgrp_grps_hdr' => 'To belong to this forum group, users must belong to ALL selected groups:',
		'fgrp_usrs_hdr' => 'Specific frontend users that also belong to this forum group:',
		'db_clean' => 'Clean Forum Tables',
		'db_clean_note' => 'If you press submit, this function will comb through the chc forum tables and attempt to repair any records that are either deleted or are missing a parent record. This function runs when ever a conference or thread is deleted in this module. More specifically, it does the following:<br />
                                                        (1) Deletes all threads that are missing a parent conference<br />
                                                        (2) Deletes all posts that are missing a parent thread or a parent conference<br />
                                                        (3) Deletes every form record where deleted = 0 and<br />
                                                        (4) Deletes all records in the post_read table (new post tracking) refering to a deleted post<br />
                                                        (5) Deletes all posts that are older than the pruning max age setting, which is set on the "forum configuration" page<br />
                                                        ',
		'no_recs' => 'NO RECORDS!',
		'what_to_do_hdr' => 'what would you like to do?',
		'submit' => 'submit',
		'cancel' => 'cancel',
		'instructions' => 'No instances of the forum plugin have been created.
											Before you can use this tool, you need to do the basic setup for
											the forum. To do this, consult the manual. If, however, you\'re in
											too much of a hurry to read the manual, these steps should get you
											started:<br /><br />
											1. Click on the title of the page that you want to hold the forum in the 
											page tree.<br />
											2. Click on the page module. Click on the new record icon in the page module.
											3. Click "chc forum" in the plugins list.<br />
											4. Set the PID (page ID, which can be found by holding the mouse cursor over 
											a page icon in the page tree) of the folder that contains your frontend users.<br />
											in the "Frontend user storage folder PID" in the forum flexform.<br />
											5. Set the "starting point" field (below the flexform) to the page or sysfolder
											in which you will store your forum records.<br />
											6. Click on the appearance tab and give your forum a title by entering it in
											the "forum title" field.<br />
											7. Click on the security tab. Enter a secret word in the corresponding field --
											this word can be anything; the forum uses it to generate secure hashes.<br />
											8. Save the plugin record by clicking on the disk icon at the top of the
											frame.<br />
											9. That\'s it -- you\'re done! If you like, you can now use the backend
											forum module to create forum records (some users find it easier).<br />
											',
	),
	'dk' => Array (
	),
	'de' => Array (
		'msg_forum_select' => 'Bitte das Forum auswählen das Sie verwalten wollen:',
		'msg_selection_select' => 'Bitte eine Funktion auswählen :',
		'title' => 'CHC Forum Administration',
		'ad_cats' => 'Kategorien verwalten',
		'ad_confs' => 'Konferenzen verwalten',
		'ad_fgroups' => 'Forum-Gruppen verwalten',
		'f_conf' => 'Forum konfigurieren',
		'addcat' => 'Kategorie hinzufügen',
		'modcat' => 'Kategorie bearbeiten',
		'delcat' => 'Kategorie löschen',
		'addconf' => 'Konferenz hinzufügen',
		'modconf' => 'Konferenz bearbeiten',
		'delconf' => 'Konferenz löschen',
		'addfgrp' => 'Forum-Gruppe hinzufügen',
		'modfgrp' => 'Forum-Gruppe bearbeiten',
		'delfgrp' => 'Forum-Gruppe löschen',
		'message_posts_del' => 'Die nachfolgenden Nachrichten (uid / Betreff) wurden permanent gelöscht, weil ihnen der Bezug zur Konferenz und/oder dem Thema fehlen:',
		'message_posts_prune_del' => 'Die nachfolgenden Nachrichten (uid / Betreff) wurden permanent gelöscht, weil sie die Zeitspanne für die Löschung erreicht haben:',
		'message_threads_del' => 'Die nachfolgenden Themen (uid / Betreff) wurden permanent gelöscht, weil sie entweder keinen Bezug zur Konferenz hatten oder weil sie keine Nachrichten enthielten:',
		'message_del' => 'Der Datenbank Bereiniger hat alle CHC Forum Tabellen überprüft, und alle Datensätze mit "deleted = 1" gelöscht. Insgesamt wurden folgenden Sätze gelöscht:',
		'message_del_lbl' => 'Gelöschte Nachrichten:',
		'message_pr_del' => 'In der Datenbank wurde auch die Tabelle "posts_read" bereinigt, die wiederum die gelesenen Nachrichten je Benutzer überwacht. Alle Verweise auf nicht mehr vorhandene Nachrichten wurden gelöscht.',
		'message_none' => 'Keine!',
		'message_add_success' => 'Datensatz hinzugefügt!',
		'message_del_success' => 'Datensatz gelöscht!',
		'message_mod_success' => 'Datensatz gespeichert!',
		'message_fconf_success' => 'Ihre Änderungen wurden erfolgreich gespeichert !',
		'mailer_forum_url_lbl' => 'Geben Sie die URL für die Website ein. Bitte den Schrägstrich am Ende nicht vergessen!<br /><br />Beispiel: http://ihredomain.de/',
		'mailer_disable_lbl' => 'Markieren um die Mailing-List Funktion abzuschalten.',
		'tmpl_path_lbl' => 'Speicherort (Pfad) für benutzerdefinierte Templates:<br /><br />Dies sollte ein relativer Pfad innerhalb der typo3 Installation sein. Lassen Sie das Feld leer, wenn Sie die Standard-Templates benutzen wollen.<br /><br />Beispiel: fileadmin/forum_templates/',
		'allowed_file_types_lbl' => 'Auflistung der erlaubten Typen für Dateianhänge (getrennt durch Komma)<br /><br />Warnung: Erteilen Sie keine Erlaubnis für php- oder html-Dateien. Eine Erlaubnis für diese Dateitypen stellt ein hohes Sicherheitsrisiko dar, weil diese Dateitypen über einen Browser ausgeführt werden können.<br /><br />Beispiel: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'Auflistung der erlaubten Mime Typen für Dateianhänge (getrennt durch Komma).<br /><br />Beispiel: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Max. Grösse Benutzer Bild (in KB)',
		'max_attach_lbl' => 'Max. Grösse Dateianhang (in KB)',
		'usrsAD_lbl' => 'Benutzer A-D',
		'usrsEH_lbl' => 'Benutzer E-H',
		'usrsIL_lbl' => 'Benutzer I-L',
		'usrsMP_lbl' => 'Benutzer M-P',
		'usrsQT_lbl' => 'Benutzer Q-T',
		'usrsUZ_lbl' => 'Benutzer U-Z',
		'add_fgrp' => 'Forum-Gruppe hinzufügen',
		'del_fgrp' => 'Forum-Gruppe löschen',
		'mod_fgrp' => 'Forum-Gruppe bearbeiten',
		'add_conf' => 'Konferenz hinzufügen',
		'del_conf' => 'Konferenz löschen',
		'mod_conf' => 'Konferenz bearbeiten',
		'add_cat' => 'Kategorie hinzufügen',
		'del_cat' => 'Kategorie löschen',
		'mod_cat' => 'Kategorie bearbeiten',
		'cat_title_hdr' => 'Bitte den Titel eingeben : (Pflichtfeld):',
		'cat_title_lbl' => 'Titel:',
		'cat_hide_lbl' => 'Verstecken:',
		'cat_grps_lbl' => 'Frontend-Gruppe die Zugriff auf diese Kategorie und die untergeordneten Konferenzen hat:',
		'cat_desc_lbl' => 'Beschreibung:',
		'cat_hide_hdr' => 'Markieren um die Kategorie zu verstecken:',
		'cat_desc_hdr' => 'Beschreibung für die Kategorie:',
		'cat_grps_hdr' => 'Kategorie Zugriff (optional):',
		'cat_fgaccess_lbl' => 'Forum-Gruppen die Zugriff auf diese Kategorie und die untergeordneten Konferenzen haben:',
		'cnf_hide_hdr' => 'Verstecken:',
		'cnf_cat_hdr' => 'Kategorie auswählen zu der die Konferenz gehört:',
		'cnf_title_hdr' => 'Den Namen der Konferenz eingeben:',
		'cnf_desc_hdr' => 'Eine Beschreibung für die Konferenz eingeben:',
		'cnf_publ_r_hdr' => 'Gäste haben Lese-Berechtigung:',
		'cnf_publ_w_hdr' => 'Gäste haben Schreib-Berechtigung:',
		'cnf_fgaccess_hdr' => 'Forum-Gruppen die Zugriff auf die Konferenz haben:',
		'cnf_fgattach_hdr' => 'Forum-Gruppen die Dateianhänge übertragen dürfen:',
		'cnf_usrs_hdr' => 'Zugeordnete Moderatoren:',
		'cnf_hide_lbl' => 'Markieren um die Konferenz zu verstecken:',
		'cnf_cat_lbl' => 'Kategorie',
		'cnf_title_lbl' => 'Name',
		'cnf_desc_lbl' => 'Beschreibung',
		'cnf_publ_r_lbl' => 'Anonymer Lese-Zugriff<br />[Wenn Sie dies markieren, können Gäste (nicht angemeldete Benutzer) Nachrichten in der Konferenz lesen.]',
		'cnf_publ_w_lbl' => 'Anonymer Schreib-Zugriff<br />[Wenn Sie dies markieren, können Gäste (nicht angemeldete Benutzer) Nachrichten in die Konferenz schreiben.]',
		'cnf_fgaccess_lbl' => 'Forum-Gruppe lesen / schreiben erlaubt',
		'cnf_fgattach_lbl' => 'Forum-Gruppe Anlage/Dateianhang erlaubt',
		'cnf_user_edit_hdr' => 'Nachricht bearbeiten:',
		'cnf_user_edit_lbl' => 'Benutzer können eigene Nachrichten bearbeiten ?',
		'fgrp_hide_lbl' => 'Verstecken:',
		'fgrp_title_lbl' => 'Titel:',
		'fgrp_desc_lbl' => 'Beschreibung:',
		'fgrp_grps_lbl' => 'Frontend-Gruppen:',
		'fgrp_hide_hdr' => 'Markieren um die Gruppe zu verstecken:',
		'fgrp_title_hdr' => 'Bitte einen Titel eingeben (Pflichtfeld):',
		'fgrp_desc_hdr' => 'Beschreibung der Forum-Gruppe:',
		'fgrp_grps_hdr' => 'Um zu dieser Forum-Gruppe zu gehören, müssen die Benutzer in ALLEN markierten Gruppen vorhanden sein:',
		'fgrp_usrs_hdr' => 'Besondere Frontend-Benutzer die auch zu dieser Forum-Gruppe gehören:',
		'db_clean' => 'Forum Tabellen bereinigen',
		'db_clean_note' => 'Wenn Sie Übertragen drücken, wird diese Funktion alle CHC Forum Tabellen überprüfen und versuchen Datensätze zu reparieren die entweder gelöscht sind oder fehlende Referenzen haben. Diese Funktion wird immer bei der Löschung von Konferenz oder Thema ausgeführt. Die Aktionen im Einzelnen:<br />
                                                        (1) Löscht alle Themen die zu keiner Konferenz gehören<br />
                                                        (2) Löscht alle Nachrichten die zu keinem Thema oder keiner Konferenz gehören<br />
                                                        (3) Löscht alle Formular-Datensätze wo "deleted = 0" und<br />
                                                        (4) Löscht alle Datensätze in der "post_read" Tabelle (neue Nachrichten-Referenz) die auf gelöschte Nachrichten zeigen<br />
                                                        (5) Löscht alle Nachrichten, die die Zeitspanne für die Löschung überschritten haben. Die Zeitspanne ist in der "Forum Konfiguration" festgelegt.<br />
                                                        ',
		'no_recs' => 'Keine Datensätze!',
		'what_to_do_hdr' => 'was möchten Sie tun?',
		'submit' => 'Übertragen',
		'cancel' => 'Abbrechen',
	),
	'no' => Array (
		'msg_forum_select' => 'Vennligst velg forumet du ønsker å administrere',
		'msg_selection_select' => 'Vennligst velg et valg fra trekk-ned menyen',
		'title' => 'CHC forum administrasjon',
		'ad_cats' => 'Vedlikehold kategorier',
		'ad_confs' => 'Vedlikehold konferanser',
		'ad_fgroups' => 'Vedlikehold forumgrupper',
		'f_conf' => 'Konfigurer forum',
		'addcat' => 'Legg til kategori',
		'modcat' => 'Endre kategori',
		'delcat' => 'Slett kategori',
		'addconf' => 'Legg til konferanse',
		'modconf' => 'Endre konferanse',
		'delconf' => 'Slett konferanse',
		'addfgrp' => 'Legg til forumgruppe',
		'modfgrp' => 'Endre forumgruppe',
		'delfgrp' => 'Slett forumgruppe',
		'message_posts_del' => 'Følgende innlegg (UID/emne) ble permanent slettet fordi det manglet en over-konferanse og/eller tråd:',
		'message_posts_prune_del' => 'Følgende innlegg (UID/emne) ble permanent slettet fordi de er eldre enn alder satt for sletting:',
		'message_threads_del' => 'Følgende tråder (UID/emne) ble permanent slettet fordi det manglet en over-konferanse eller fordi de inneholdt ingen poster:',
		'message_del' => 'DB renser (DB cleaner) skannet alle chc_forum tabeller, og slettet alle elementer der slett=1. Totalt ble følgende nummer av elementer slettet:',
		'message_del_lbl' => 'Slettede innlegg',
		'message_pr_del' => 'DB renser (DB cleaner) renset også opp post_read tabellen, som holder orden på hvilke innlegg brukeren har lest. Alle referanser til ikke eksisterende innlegg ble slettet.',
		'message_none' => 'Ingen!',
		'message_add_success' => 'Element lagt til!',
		'message_del_success' => 'Element slettet!',
		'message_mod_success' => 'Element endret!',
		'message_fconf_success' => 'Dine endringer av forumkonfigurasjonen er lagret!',
		'mailer_forum_url_lbl' => 'Legg til URL for ditt nettsted. Ikke glem avsluttende skråstrek!<br /><br />Eksempel:http://dittdomene.com/',
		'mailer_disable_lbl' => 'Kryss av her for å slå av epostliste funksjonen.',
		'tmpl_path_lbl' => 'Adresse (path) til selvvalgt mal for forumet:<br /><br />Børe være relativ sti fra rotten på din TYPO3 installasjon. La være tom for å bruke standard template.<br /><br />Eksempel: fileadmin/forum_templates/',
		'allowed_file_types_lbl' => 'kommaseparert liste over tillatte typer for filvedlegg<br /><br />VARSEL: Ikke tillatt php or html filer som vedlegg. Gjøre det medfører en sikkerhetsrisiko siden alle filer som vedlegges kan kjøres fra nettleser<br /><br />Eksempel: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'Kommaseparert liste over tillatte mime-typer for vedlegg.<br /><br />Eksempel: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Maks størrelse for opplasting av brukerbilde (i kb)',
		'max_attach_lbl' => 'Maks størrelse på vedlegg (i kb)',
		'usrsAD_lbl' => 'Brukere A-D',
		'usrsEH_lbl' => 'Brukere E-H',
		'usrsIL_lbl' => 'Brukere I-L',
		'usrsMP_lbl' => 'Brukere M-P',
		'usrsQT_lbl' => 'Brukere Q-T',
		'usrsUZ_lbl' => 'Brukere U-Å',
		'add_fgrp' => 'Legg til en forumgruppe',
		'del_fgrp' => 'Slett en forumgruppe',
		'mod_fgrp' => 'Endre en forumgruppe',
		'add_conf' => 'Legg til en konferanse',
		'del_conf' => 'Slett en konferanse',
		'mod_conf' => 'Endre en konferanse',
		'add_cat' => 'Legg til en kategory',
		'del_cat' => 'Slett en kategori',
		'mod_cat' => 'Endre en kategori',
		'cat_title_hdr' => 'Vennligst skriv inn tittel (obligatorisk):',
		'cat_title_lbl' => 'Tittel:',
		'cat_hide_lbl' => 'Skjul:',
		'cat_grps_lbl' => 'Frontend gruppe:',
		'cat_desc_lbl' => 'Kategoribeskrivelse:',
		'cat_hide_hdr' => 'Kryss av for å skjule denne kategorien:',
		'cat_desc_hdr' => 'Skriv inn beskrivelse for denne kategorien:',
		'cat_grps_hdr' => 'Kategoritilgang (valgfritt)',
		'cat_fgaccess_lbl' => 'Forumgrupper som har tilgang til denne kategorien og dens underkategoier:',
		'cnf_hide_hdr' => 'Skjul:',
		'cnf_cat_hdr' => 'Velg kategorien som denne konferansen skal høre til:',
		'cnf_title_hdr' => 'Skriv inn navn på denne konferansen:',
		'cnf_desc_hdr' => 'Skriv inn beskrivelse for denne konferansen:',
		'cnf_publ_r_hdr' => 'Kryss av for å gi lesetilgang til anonyme brukere:',
		'cnf_publ_w_hdr' => 'Kryss av for å gi skrivetilgang til anonyme brukere:',
		'cnf_fgaccess_hdr' => 'Forumgrupper som har tilgang til denne konferansen:',
		'cnf_fgattach_hdr' => 'Forumgrupper som kan vedlegg filer til innlegg:',
		'cnf_usrs_hdr' => 'Bruker med tillatelse til å modere denne konferansen',
		'cnf_hide_lbl' => 'Kryss av for å skjule denne konferansen:',
		'cnf_cat_lbl' => 'Kategori',
		'cnf_title_lbl' => 'Konferansenavn',
		'cnf_desc_lbl' => 'Konferansebeskrivelse',
		'cnf_publ_r_lbl' => 'Lesetilgang for anonym bruker<br />[Krysser du av, vil gjestebrukere (ikke logget inn) ha mulighet til å lese innlegg i denne konferansen.]',
		'cnf_publ_w_lbl' => 'Skrivetilgang for anonym bruker<br />[Krysser du av, vil gjestebrukere (ikke logget inn) ha mulighet til å lese innlegg i denne konferansen.]',
		'cnf_fgaccess_lbl' => 'Forumgruppe lese/skrivetilgang',
		'cnf_fgattach_lbl' => 'Forumgruppe vedlegg tilgang',
		'cnf_user_edit_hdr' => 'Innleggsredigering:',
		'cnf_user_edit_lbl' => 'Tillat brukerene å regidere deres egene innlegg?',
		'fgrp_hide_lbl' => 'Skjul:',
		'fgrp_title_lbl' => 'Tittel:',
		'fgrp_desc_lbl' => 'Forumgruppe beskrivelse:',
		'fgrp_grps_lbl' => 'Frontendegruppe:',
		'fgrp_hide_hdr' => 'Kryss av for å skjule denne gruppen:',
		'fgrp_title_hdr' => 'Vennligst skriv inn tittel (obligatorisk):',
		'fgrp_desc_hdr' => 'Skriv inn bekrivelse for denne gruppen:',
		'fgrp_grps_hdr' => 'Får å tilhøre denne gruppen, må brukere tilhøre alle valgte grupper',
		'fgrp_usrs_hdr' => 'Spesifikke frontendbruker som også tilhører denne forumgruppen:',
		'db_clean' => 'Rens forumtabeller',
		'db_clean_note' => 'Desom du presser send (submit), vil denne funksjonen se gjennom chc forum tabeller og søke å reparere alle elementer (records) som enten er slettet eller mangler foreldre. Denne funksjonen kjører hver gang en konferanse eller tråd slettes i denne modulen. I detalj gjør den følgende:<br />
(1) Sletter alle tråder som mangler tilknytning til konferanse<br />
(2) Sletter alle innlegg som mangler tilknytning til tråder eller konferanse<br />
(3) Sletter alle form elementer (record) hvor slettet = 0 og <br />
(4) Sletter alle innlegg i post_read tabell (nye poster) med referanse til slettede innlegg<br />
(5) Sletter alle innlegg som er eldre enn alder satt for sletting (settes i forumkonfigurasjon)<br />',
		'no_recs' => 'Ingen elementer:',
		'what_to_do_hdr' => 'Hva har du lyst til å gjøre?',
		'submit' => 'Send',
		'cancel' => 'Avbryt',
	),
	'it' => Array (
		'msg_forum_select' => 'Seleziona il forum che intendi amministrare:',
		'msg_selection_select' => 'Seleziona un\'opzione dal menù a tendina',
		'title' => 'Amministrazione CHC Forum',
		'ad_cats' => 'Gestisci le Categorie',
		'ad_confs' => 'Gestisci le Conferenze',
		'ad_fgroups' => 'Gestisci i Gruppi dei Forum',
		'f_conf' => 'Configura Forum',
		'addcat' => 'Aggiungi Categoria',
		'modcat' => 'Modifica Categoria',
		'delcat' => 'Cancella Categoria',
		'addconf' => 'Aggiungi Conferenza',
		'modconf' => 'Modifica Conferenza',
		'delconf' => 'Cancella Conferenza',
		'addfgrp' => 'Aggiungi Gruppo dei Forum',
		'modfgrp' => 'Modifica Gruppo dei Forum',
		'delfgrp' => 'Cancella Gruppo dei Forum',
		'message_posts_del' => 'I seguenti MESSAGGI (uid / titolo) sono stati cancellati definitivamente perchè non appartenevano ad alcuna conferenza e/o discussione',
		'message_posts_prune_del' => 'I seguenti MESSAGGI (uid / titolo) sono stati cancellati definitivamente perchè avevano superato il limite di tempo per la pulizia',
		'message_threads_del' => 'Le seguenti DISCUSSIONI (uid / titolo) sono state cancellate definitivamente perchè non appartenevano a nessuna conferenza o perchè non contenevano messaggi:',
		'message_del' => 'Il pulitore del DB ha scansionato tutte le tabelle di chc_forum e ha cancellato tutti i record dove "deleted = 1". In totale, ha cancellato il seguente numero di records:',
		'message_del_lbl' => 'Cancella Messaggi:',
		'message_pr_del' => 'Il pulitore del DB ha anche ripulito la tebella "posts_read", che tiene traccia di quali messaggi ogni utente ha letto. Ogni record per cui non esiste un messaggio corrispondente, è stato cancellato.',
		'message_none' => 'Nessuno!',
		'message_add_success' => 'Record aggiunto correttamente!',
		'message_del_success' => 'Record cancellato correttamente!',
		'message_mod_success' => 'Record modificato correttamente!',
		'message_fconf_success' => 'Le modifiche alla configurazione del forum sono state salvate!',
		'mailer_forum_url_lbl' => 'Inserisci l\'URL del tuo sito. Non dimenticare lo slash finale! <br /><br />Esempio: http://tuodominio.it/',
		'mailer_disable_lbl' => 'Spunta questo box per disabilitare la mailing list.',
		'tmpl_path_lbl' => 'Percorso dei templates personalizzati per i forum: <br /><br />Dovrebbe essere un percorso relativo, partendo dalla cartella radice della tua installazione di typo3. Lascia questo campo vuoto per utilizzare i templates predefiniti per i forum.<br /><br />Esempio: fileadmin/forum_templates/',
		'allowed_file_types_lbl' => 'Valori separati da virgola dei tipi di files permessi per gli allegati.<br /><br />ATTENZIONE: Non permettete l\'inserimento di files php o html come allegati. Così facendo si crea un grave rischio per la sicurezza in quanto tutti i file allegati potenzialmente possono venire eseguiti da un browser.<br /><br />Esempio: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'Valori separati da virgola dei mime types permessi per gli allegati.<br /><br />Esempio: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Dimensione massima per la foto utente (in kb)',
		'max_attach_lbl' => 'Dimensione massima degli allegati (in kb)',
		'usrsAD_lbl' => 'Utenti A-D',
		'usrsEH_lbl' => 'Utenti E-H',
		'usrsIL_lbl' => 'Utenti I-L',
		'usrsMP_lbl' => 'Utenti M-P',
		'usrsQT_lbl' => 'Utenti Q-T',
		'usrsUZ_lbl' => 'Utenti U-Z',
		'add_fgrp' => 'Aggiungi un gruppo dei forum',
		'del_fgrp' => 'Cancella un gruppo dei forum',
		'mod_fgrp' => 'Modifica un gruppo dei forum',
		'add_conf' => 'Aggiungi una conferenza',
		'del_conf' => 'Cancella una conferenza',
		'mod_conf' => 'Modifica una conferenza',
		'add_cat' => 'Aggiungi una categoria',
		'del_cat' => 'Cancella una categoria',
		'mod_cat' => 'Modifica una categoria',
		'cat_title_hdr' => 'Inserisci un titolo (necessario):',
		'cat_title_lbl' => 'Titolo:',
		'cat_hide_lbl' => 'Nascondi:',
		'cat_grps_lbl' => 'Gruppi di frontend che possono accedere a questa categoria ed alle conferenze appartenenti ad essa:',
		'cat_desc_lbl' => 'Descrizione Categoria:',
		'cat_hide_hdr' => 'Seleziona per nascondere questa categoria:',
		'cat_desc_hdr' => 'Inserisci una descrizione per questa categoria:',
		'cat_grps_hdr' => 'Accesso alla Categoria (opzionale):',
		'cat_fgaccess_lbl' => 'Gruppi dei forum che possono accedere a questa categoria ed alle conferenze appartenenti ad essa:',
		'cnf_hide_hdr' => 'Nascondi:',
		'cnf_cat_hdr' => 'Seleziona la categoria a cui appartiene questa conferenza:',
		'cnf_title_hdr' => 'Inserisci il nome di questa conferenza:',
		'cnf_desc_hdr' => 'Inserisci una descrizione per questa conferenza:',
		'cnf_publ_r_hdr' => 'Seleziona questo box per dare i permessi di lettura agli utenti anonimi:',
		'cnf_publ_w_hdr' => 'Spunta questo box per permettere l\'invio di messaggi agli utenti anonimi:',
		'cnf_fgaccess_hdr' => 'Gruppi dei forum che possono accedere a questa conferenza:',
		'cnf_fgattach_hdr' => 'Gruppi dei forum che possono allegare files ai messaggi:',
		'cnf_usrs_hdr' => 'Utenti abilitati a moderare questa conferenza:',
		'cnf_hide_lbl' => 'Spunta per nascondere questa conferenza:',
		'cnf_cat_lbl' => 'Categoria',
		'cnf_title_lbl' => 'Nome Conferenza',
		'cnf_desc_lbl' => 'Descrizione Conferenza',
		'cnf_publ_r_lbl' => 'Permesso di Lettura Anonimo<br />[Se spunti questa opzione, gli utenti che non hanno effettuato il login potranno leggere i messaggi in questa conferenza]',
		'cnf_publ_w_lbl' => 'Permesso di Invio Anonimo<br />[Se spunti questa opzione, gli utenti che non hanno effettuato il login potranno inserire nuovi messaggi in questa conferenza.]',
		'cnf_fgaccess_lbl' => 'Permessi lettura / inserimento per i Gruppi dei forum',
		'cnf_fgattach_lbl' => 'Permessi per gli allegati per i Gruppi dei forum',
		'cnf_user_edit_hdr' => 'Modifica messaggi:',
		'cnf_user_edit_lbl' => 'Consenti agli utenti di modificare i propri messaggi?',
		'fgrp_hide_lbl' => 'Nascondi:',
		'fgrp_title_lbl' => 'Titolo:',
		'fgrp_desc_lbl' => 'Descrizione Gruppo dei Forum:',
		'fgrp_grps_lbl' => 'Gruppi di Frontend:',
		'fgrp_hide_hdr' => 'Spunta per nascondere questo gruppo:',
		'fgrp_title_hdr' => 'Inserisci un titolo (necessario):',
		'fgrp_desc_hdr' => 'Inserisci una descrizione per questo gruppo:',
		'fgrp_grps_hdr' => 'Per appartenere a questo gruppo dei forum, gli utenti devono appartenere a TUTTI i gruppi selezionati:',
		'fgrp_usrs_hdr' => 'Specifica gli utenti di frontend che appartengono anche a questo gruppo dei forum:',
		'db_clean' => 'Pulisci le Tabelle dei Forum',
		'db_clean_note' => 'Cliccando su invia, questa funzione cercherà fra le tabelle di chc forum e proverà a riparare qualsiasi record che è stato cancellato o a cui manca un record genitore.
Questa funzione si attiva ogni volta che una conferenza o una discussione viene cancellata in questo modulo. Più precisamente, esegue le seguenti operazioni:<br />
(1) Cancella tutte le discussioni che non appartengono ad alcuna conferenza<br />
(2) Cancella tutti i messaggi che non appartengono ad alcuna discussione o conferenza<br />
(3) Cancella ogni record in cui "deleted=0" e<br />
(4) Cancella tutti i record nella tabella "post_read" (controllo nuovi messaggi) che fanno riferimento ad un messaggio non più esistente<br />
(5) Cancella tutti i messaggi che sono più vecchi dell\'età massima di pulitura messaggi, che viene settata nella pagina di "configurazione forum"<br />',
		'no_recs' => 'NON CI SONO RECORD!',
		'what_to_do_hdr' => 'cosa vuoi fare?',
		'submit' => 'invia',
		'cancel' => 'annulla',
	),
	'fr' => Array (
	),
	'es' => Array (
		'msg_forum_select' => 'Por favor, elige el foro que deseas administrar',
		'msg_selection_select' => 'Por favor, elige una opción de la lista desplegable',
		'title' => 'Administación del Foro CHC',
		'ad_cats' => 'Administrar Categorías',
		'ad_confs' => 'Administrar Conferencias',
		'ad_fgroups' => 'Administrar Grupos del Foro',
		'f_conf' => 'Configurar el Foro',
		'addcat' => 'Añadir una Categoría',
		'modcat' => 'Modificar una Categoría',
		'delcat' => 'Borrar una Categoría',
		'addconf' => 'Añadir una Conferencia',
		'modconf' => 'Modificar una Conferencia',
		'delconf' => 'Borrar una Conferencia',
		'addfgrp' => 'Añadir un Grupo del Foro',
		'modfgrp' => 'Modificar un Grupo del Foro',
		'delfgrp' => 'Borrar un Grupo del Foro',
		'message_posts_del' => 'Los siguientes MENSAJES (uid / asunto) se borrarán permanentemente porque pertenecen a un hilo o conferencia que no existe:',
		'message_posts_prune_del' => 'Los siguientes MENSAJES (uid / subject) se borrarán permanentemente ya que sobrepasan la fecha límite:',
		'message_threads_del' => 'Los siguientes HILOS (uid / asunto) serán borrados permanentemente ya que o bien no pertenecen a ninguna conferencia o no contienen mensajes:',
		'message_del' => 'El limpiador de la BD chequeó todas las tablas del Foro CHC, y borró todos los registros donde el campo deleted = 1. En total, borro el siguiente nº de registros:',
		'message_del_lbl' => 'Mensajes borrados:',
		'message_pr_del' => 'El limpiador de la BD también limpió la tabla post_read que almacena un seguimiento de los mensajes leídos por cada usuario. Cualquier entrada que no correspondía a algún mensaje fue eliminada.',
		'message_none' => '¡Ninguno!',
		'message_add_success' => '¡Registro añadido correctamente!',
		'message_del_success' => '¡Registro eliminado correctamente!',
		'message_mod_success' => '¡Registro modificado correctamente!',
		'message_fconf_success' => '¡Tus modificaciones de la configuración del foro han sido almacenadas!',
		'mailer_forum_url_lbl' => 'Introduzca la URL de su sitio. ¡No olvide la última barra!<br /><br />Por ejemplo: http://tudominio.com/',
		'mailer_disable_lbl' => 'Activa esta opción para desactivar las características de lista de correo.',
		'tmpl_path_lbl' => 'Ruta a las plantillas personales del foro:<br /><br /> Esto debería ser una ruta relativa desde la raíz de tu instalación de typo3. Deje esto en blanco para usar las plantillas por defecto del foro.<br /><br />Por ejemplo: fileadmin/forum_templates/',
		'allowed_file_types_lbl' => 'Lista de tipos de ficheros separados por comas<br /><br />AVISO: No permitas que se inserten archivos php o html. Hacer eso te expone a importantes problemas de seguridad ya que tales archivos podrían ser ejecutados potencialmente desde un navegador.<br /><br />Por ejemplo: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'Lista de archivos multimedia (MIME) permitidos al añadir separados por comas. <br /><br />Por ejemplo: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Tamaño máximo de imágenes subidas al servido (en kb)',
		'max_attach_lbl' => 'Tamaño máximo de subida (en kb)',
		'usrsAD_lbl' => 'Usuarios A-D',
		'usrsEH_lbl' => 'Usuarios E-H',
		'usrsIL_lbl' => 'Usuarios I-L',
		'usrsMP_lbl' => 'Usuarios M-P',
		'usrsQT_lbl' => 'Usuarios Q-T',
		'usrsUZ_lbl' => 'Usuarios U-Z',
		'add_fgrp' => 'Añadir un grupo del foro',
		'del_fgrp' => 'Borrar un grupo del foro',
		'mod_fgrp' => 'Modificar un grupo del foro',
		'add_conf' => 'Añadir una conferencia',
		'del_conf' => 'Borrar una conferencia',
		'mod_conf' => 'Modificar una conferencia',
		'add_cat' => 'Añadir una categoría',
		'del_cat' => 'Borrar una categoría',
		'mod_cat' => 'Modificar una categoría',
		'cat_title_hdr' => 'Por favor introduzca un título (obligatorio):',
		'cat_title_lbl' => 'Título:',
		'cat_hide_lbl' => 'Ocultar:',
		'cat_grps_lbl' => 'Grupos del Frontend:',
		'cat_desc_lbl' => 'Descripción de la Categoría:',
		'cat_hide_hdr' => 'Comprobar a esconder esta categoría:',
		'cat_desc_hdr' => 'Introduzca una descripción para esta categoría',
		'cat_grps_hdr' => 'Acceso a categoría (opcional):',
		'cat_fgaccess_lbl' => 'Grupos del foro que pueden acceder a esta categoría y a sus conferencias:',
		'cnf_hide_hdr' => 'Ocultar:',
		'cnf_cat_hdr' => 'Seleccionar la categoría a la que pertenece esta conferencia:',
		'cnf_title_hdr' => 'Introduzca el nombre de esta conferencia:',
		'cnf_desc_hdr' => 'Introduzca una descripción para esta conferencia:',
		'cnf_publ_r_hdr' => 'Selecciona esta opción para permitir acceso de lectura a usuarios anónimos:',
		'cnf_publ_w_hdr' => 'Selecciona esta opción para permitir enviar mensajes a usuarios anónimos:',
		'cnf_fgaccess_hdr' => 'Grupos del foro que pueden acceder a esta conferencia:',
		'cnf_fgattach_hdr' => 'Grupos del foro que puede añadir archivos a sus mensajes:',
		'cnf_usrs_hdr' => 'Usuarios asignados para moderar esta conferencia:',
		'cnf_hide_lbl' => 'Selecciona esta opción para ocultar la conferencia',
		'cnf_cat_lbl' => 'Categoría',
		'cnf_title_lbl' => 'Nombre de la conferencia',
		'cnf_desc_lbl' => 'Descripción de la conferencia',
		'cnf_publ_r_lbl' => 'Acceso de lectura anónimo<br />[Si seleccionas esto, los usuarios invitados (que no han hecho login) podrán leer los mensajes de esta conferencia.]',
		'cnf_publ_w_lbl' => 'Acceso de escritura anónimo<br />[Si seleccionas esto, los usuarios invitados (los que no han hecho login) podrán enviar nuevos mensajes en esta conferencia.]',
		'cnf_fgaccess_lbl' => 'Permiso del grupo del foro para lectura',
		'cnf_fgattach_lbl' => 'Permiso del grupo del foro para añadir ficheros a sus mensajes',
		'cnf_user_edit_hdr' => 'Edición del envío:',
		'cnf_user_edit_lbl' => '¿Permitir a los usuarios editar sus propios envíos?',
		'fgrp_hide_lbl' => 'Ocultar:',
		'fgrp_title_lbl' => 'Título:',
		'fgrp_desc_lbl' => 'Descripción del Grupo del Foro:',
		'fgrp_grps_lbl' => 'Grupos del Fronend:',
		'fgrp_hide_hdr' => 'Selecciona esta opción para ocultar este grupo',
		'fgrp_title_hdr' => 'Por favor, introduce un título (obligatorio):',
		'fgrp_desc_hdr' => 'Introduzca una descripción para este grupo:',
		'fgrp_grps_hdr' => 'Para pertenecer a este grupo del foro, los usuarios deben pertenecer al grupo ALL (TODOS)',
		'fgrp_usrs_hdr' => 'Usuarios específicos del frontend que también pertenecen a este grupo del foro:',
		'db_clean' => 'Limpiar las Tablas del foro',
		'db_clean_note' => 'Si pulsas envia, esta función escaneará todas las tablas del Foro CHC e intentará reparar cualquier registro q tenga un padre eliminado o perdido. Esta función se ejecuta cuando una conferencia o hilo se borra en el módulo. Más específicamente, hace lo siguiente:<br />
(1) Borra todos los hilos que pertenezcan a una conferencia que no exista <br />
(2) Borra todos los mensajes que pertenezcan a un hilo o una conferencia q no exista <br />
(3) Borra todos los registros que tengan deleted = 0 y<br />
(4) Borra todos los registros de la tabla post_read (control de mensajes recientes) que hagan referencia a un mensaje borrado<br />
(5) Borra todos los mensajes que sean más antiguos que la edad de cote establecida, ésta se establece en la página de configuración del foro<br />',
		'no_recs' => '¡NINGÚN REGISTRO!',
		'what_to_do_hdr' => '¿Qué le gustaría hacer?',
		'submit' => 'envío',
		'cancel' => 'cancelar',
	),
	'nl' => Array (
		'msg_forum_select' => 'Selecteer het forum dat je wilt beheren:',
		'msg_selection_select' => 'Selecteer een optie uit het drop-down menu',
		'title' => 'CHC forumbeheer',
		'ad_cats' => 'Manage categoriën',
		'ad_confs' => 'Manage conferenties',
		'ad_fgroups' => 'Manage forumgroepen',
		'f_conf' => 'Configureer forum',
		'addcat' => 'Toevoegen forum',
		'modcat' => 'Bewerk forum',
		'delcat' => 'Verwijder forum',
		'addconf' => 'Toevoegen conferentie',
		'modconf' => 'Bewerk conferentie',
		'delconf' => 'Verwijder conferentie',
		'addfgrp' => 'Toevoegen forumgroep',
		'modfgrp' => 'Bewerk forumgroep',
		'delfgrp' => 'Verwijder forumgroep',
		'message_posts_del' => 'De volgende berichten (uid / onderwerp) zijn blijvend verwijderd, omdat een parentconferentie en/of discussielijn niet aanwezig waren:',
		'message_posts_prune_del' => 'De volgende berichten (uid / onderwerp) zijn permanent verwijderd, omdat ze de pruningleeftijd overschreden hebben:',
		'message_threads_del' => 'De volgende DISCUSSIES (uid / onderwerp) zijn blijvend verwijderd, omdat een parentconferentie niet aanwezig was:',
		'message_del' => 'De DBcleaner heeft de chc-forumtabellen gescanned en alle records verwijderd "WHERE DELETED = 1".<br />Aantal verwijderde records:',
		'message_del_lbl' => 'Verwijderde berichten:',
		'message_pr_del' => 'De DBcleaner heeft ook de post_read tabel opgeschoond. Deze tabel houdt bij welke berichten iedere gebruiker gelezen heeft. Bijdragen gekoppeld aan een niet langer bestaand bericht zijn verwijderd!',
		'message_none' => 'Geen!',
		'message_add_success' => 'Record toegevoegd!',
		'message_del_success' => 'Record verwijderd!',
		'message_mod_success' => 'Record gewijzigd!',
		'message_fconf_success' => 'De wijzigingen aan de forumconfiguratie zijn opgeslagen!',
		'mailer_forum_url_lbl' => 'URL van deze website. Vergeet de laatste slash niet!<br /><br />Voorbeeld: http://www.domein.nl/',
		'mailer_disable_lbl' => 'Selecteer om de mailinglijst te deactiveren:',
		'tmpl_path_lbl' => 'Pad naar eigen forum templates:<br /><br />Dit is een relatief pad vanuit de root van de TYPO3 installatie. Niet invullen als je de standaard forum templates wilt gebruiken.<br /><br /> Voorbeeld: fileadmin/forum_templates/',
		'allowed_file_types_lbl' => 'Kommagescheiden lijst van toegestane bestandtypes<br /><br />WAARSCHUWING: Sta geen php of html bestanden toe als bijlagen. Deze kunnen een enorm veligheidsrisico betekenen, omdat deze in de browser uitgevoerd kunnen worden.<br /><br />Voorbeeld: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'Kommagescheiden lijst van toegestane mimetypes<br /><br />Voorbeeld: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Max uploadgrootte voor afbeeldingen (in kb)',
		'max_attach_lbl' => 'Max bijlagegrootte (in kb)',
		'usrsAD_lbl' => 'Gebruikers A-D',
		'usrsEH_lbl' => 'Gebruikers E-H',
		'usrsIL_lbl' => 'Gebruikers I-L',
		'usrsMP_lbl' => 'Gebruikers M-P',
		'usrsQT_lbl' => 'Gebruikers Q-T',
		'usrsUZ_lbl' => 'Gebruikers U-Z',
		'add_fgrp' => 'Toevoegen forumgroep',
		'del_fgrp' => 'Verwijder forumgroep',
		'mod_fgrp' => 'Bewerk forumgroep',
		'add_conf' => 'Toevoegen conferentie',
		'del_conf' => 'Verwijder conferentie',
		'mod_conf' => 'Bewerk conferentie',
		'add_cat' => 'Toevoegen categorie',
		'del_cat' => 'Verwijder categorie',
		'mod_cat' => 'Bewerk categorie',
		'cat_title_hdr' => 'Titel (verplicht):',
		'cat_title_lbl' => 'Titel:',
		'cat_hide_lbl' => 'Verberg:',
		'cat_grps_lbl' => 'Frontendgebruikers:',
		'cat_desc_lbl' => 'Omschrijving categorie:',
		'cat_hide_hdr' => 'Aanvinken om categorie te verbergen:',
		'cat_desc_hdr' => 'Omschrijving voor deze categorie:',
		'cat_grps_hdr' => 'Toegang voor categorie (optioneel):',
		'cat_fgaccess_lbl' => 'Forum groepen welke toegang hebben to deze categorie en onderliggende conferenties',
		'cnf_hide_hdr' => 'Verberg:',
		'cnf_cat_hdr' => 'Selecteer de categorie waar deze conferentie toe behoort:',
		'cnf_title_hdr' => 'Naam van deze conferentie:',
		'cnf_desc_hdr' => 'Omschrijving voor deze conferentie:',
		'cnf_publ_r_hdr' => 'Selecteer om leesrechten toe te kennen aan anonieme gebruikers:',
		'cnf_publ_w_hdr' => 'Selecteer om schrijfrechten toe te kennen aan anonieme gebruikers:',
		'cnf_fgaccess_hdr' => 'Forumgroepen met  toegang tot deze conferentie:',
		'cnf_fgattach_hdr' => 'Forumgroepen die bijlagen aan de berichten moegen toevoegen:',
		'cnf_usrs_hdr' => 'Gebruikers die deze conferentie modereren:',
		'cnf_hide_lbl' => 'Aanvinken om conferentie te verbergen:',
		'cnf_cat_lbl' => 'Categorie',
		'cnf_title_lbl' => 'Naam conferentie',
		'cnf_desc_lbl' => 'Omschrijving conferentie',
		'cnf_publ_r_lbl' => 'Leesrechten voor anonieme gebruikers<br />[Als je dit aanvinkt dan kunnen ook niet ingelogde gebruikers berichten in deze conferentie lezen.]',
		'cnf_publ_w_lbl' => 'Schrijfrechten voor anonieme gebruikers<br />[Als je dit aanvinkt dan kunnen ook niet ingelogde gebruikers berichten aan deze conferentie toevoegen.]',
		'cnf_fgaccess_lbl' => 'Lees/schrijfrechten voor deze forumgroep',
		'cnf_fgattach_lbl' => 'Bijlagerechten voor deze forumgroep',
		'cnf_user_edit_hdr' => 'Bericht bewerken:',
		'cnf_user_edit_lbl' => 'Toestaan dat gebruikers eigen berichten kunnen aanpassen?',
		'fgrp_hide_lbl' => 'Verberg:',
		'fgrp_title_lbl' => 'Titel:',
		'fgrp_desc_lbl' => 'Omschrijving forumgroep:',
		'fgrp_grps_lbl' => 'Frontendgroepen:',
		'fgrp_hide_hdr' => 'Aanvinken om deze groep te verbergen:',
		'fgrp_title_hdr' => 'Titel invullen! (verplicht):',
		'fgrp_desc_hdr' => 'Omschrijving voor deze groep:',
		'fgrp_grps_hdr' => 'De gebruiker moet van ALLE geselecteerde groepen lid zijn om tot deze forumgroep te kunnen behoren:',
		'fgrp_usrs_hdr' => 'Specifieke frontendgebruikers die ook tot deze forumgroepen behoren:',
		'db_clean' => 'Forumtabellen opschonen',
		'db_clean_note' => 'Deze functie spit door de chc forumtabellen en probeert records te repareren die verwijderd zijn of een parentrecord missen. Deze functie wordt uitgevoerd als er een conferentie of discussielijn wordt verwijderd in deze module. 
<ol>
  <li>Verwijderd alle discussielijnen zonder parentconferentie</li>
  <li>Verwijderd berichten zonder parentdiscussielijn of parentconferentie</li>
  <li>Verwijderd elk formulierrecord WHERE DELETED = 0</li>
  <li>Verwijderd alle records in de post_read tabel (new post tracking) refererend aan een verwijderd bericht</li>
</ol>',
		'no_recs' => 'GEEN RECORDS:',
		'what_to_do_hdr' => 'Wat wilt u doen?',
		'submit' => 'OK',
		'cancel' => 'Annuleren',
		'instructions' => 'Er zijn nog geen forums gecreeerd. Voordat u deze tool kunt gebruiken moet u de basis setup voor het forum uitvoeren. Hoe dit te doen kunt u in de handleiding lezen. Als u echter te veel haast heeft en de handleiding niet kunt lezen, dan zullen de volgende stappen u op weg helpen:
<ol>
<li>Klik op de titel van de pagina welke het forum moet gaan bevatten in de paginaboom.</li>
<li>Klik op de pagina module. Klik op het nieuw record icoontje in de pagina module.<br />
<li>Klik "chc forum" in the plugins list.</li>
<li>Stel de PID (Pagina ID, welke gevonden kan worden door de muis boven een icoon van een pagina in de paginaboom te houden) van de folder welke uw frontend gebruikers bevat.</li>
in de "Frontend gebruiker oplsag folder PID" in het fleform van de forum plugin.<br />
<li>Stel het "start punt" veld (onder het flexform) in op de pagina of folder waarin de forum records opgeslagen dienen te worden.</li>
<li>Klik op het weergave tabblad en geef het forum een naam.</li>
<li>Klik op het beveiligings tabblad. Voer een geheim woord in het overeenkomstige veld -- dit woord kan alles zijn; het forum gebruikt deze om veilige hashes te maken.</li>
<li>Bewaar de plugin instellingen door op het icoontje met het symbool van een diskette te klikken bovenin het scherm.</li>
<li>Dat is alles, u bent klaar. Als u wiult kunt u nu de backend forum module gebruiken om forum records te creeren. (Sommige gebruikers vinden dit handiger)</li>
</ol>',
	),
	'cz' => Array (
		'msg_forum_select' => 'Prosím zvolte fórum, které byste chtìli spravovat:',
		'msg_selection_select' => 'Prosím zvolte jednu monost ze stahovací nabídky',
		'title' => 'Správa CHC fóra',
		'ad_cats' => 'Správa kategorií',
		'ad_confs' => 'Správa konferencí',
		'ad_fgroups' => 'Správa skupin fóra',
		'f_conf' => 'Nastavit fórum',
		'addcat' => 'Pøidat kategorii',
		'modcat' => 'Upravit kategorii',
		'delcat' => 'Vymazat kategorii',
		'addconf' => 'Pøidat konferenci',
		'modconf' => 'Upravit konferenci',
		'delconf' => 'Vymazat konferenci',
		'addfgrp' => 'Pøidat skupinu fóra',
		'modfgrp' => 'Upravit skupinu fóra',
		'delfgrp' => 'Vymazat skupinu fóra',
		'message_posts_del' => 'Následující PØÍSPÌVKY (uid / pøedmìt) byly trvale vymazány, protoe v nich chybìla nadøazená konference a/nebo téma:',
		'message_posts_prune_del' => 'Následující PØÍSPÌVKY (uid / pøedmìt) byly trvale vymazány, protoe pøekroèily stáøí pro vymazání:',
		'message_threads_del' => 'Následující TÉMATA (uid / pøedmìt) byla trvale vymazána, protoe v nich chybìla nadøazená konference nebo protoe neobsahovaly ádné pøíspìvky:',
		'message_del' => 'Èistiè DB pøeèetl všechny tabulky chc_forum a vymazal všechny záznamy, kde vymazané = 1. Celkem vymazal následující poèet záznamù:',
		'message_del_lbl' => 'Vymazané pøíspìvky:',
		'message_pr_del' => 'Èistiè DB rovnì vyèistil tabulku posts_read, kde se sleduje, které pøíspìvky si kadı uivatel pøeèetl. Všechny záznamy, ke kterım ji neexistuje pøíslušnı pøíspìvek, byly vymazány.',
		'message_none' => 'ádné!',
		'message_add_success' => 'Záznam úspìšnì pøidán!',
		'message_del_success' => 'Záznam úspìšnì vymazán!',
		'message_mod_success' => 'Záznam úspìšnì zmìnìn!',
		'message_fconf_success' => 'Vaše zmìny konfigurace fóra byly uloeny!',
		'mailer_forum_url_lbl' => 'Zadejte URL vaší stránky. Nezapomeòte závìreèné lomítko! <br /><br />Pøíklad: http://yourdomain.com/',
		'mailer_disable_lbl' => 'Zaškrtnutím tohoto okénka vypnete funkce poštovního seznamu.',
		'tmpl_path_lbl' => 'Cesta k vlastním šablonám fóra::<br /><br />Mìlo by jít o relativní cestu od koøene vaší instalace typo3. Pokud pole nevyplníte, pouijí se vıchozí šablony fóra. <br /><br />Pøíklad: fileadmin/forum_templates/',
		'allowed_file_types_lbl' => 'Seznam typù souborù povolenıch jako pøílohy, oddìlenıch èárkou<br /><br />VAROVÁNÍ: Nepovolujte jako pøílohy php nebo html soubory. Pøedstavuje to závané bezpeènostní riziko, protoe všechny pøiloené soubory mohou potenciálnì bıt spuštìny z prohlíeèe.<br /><br />Pøíklad: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'Seznam povolenıch mime typù pro pøílohy, oddìlenıch èárkou.<br /><br />Pøíklad: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Max velikost nahrávaného obrázku uivatele (v kb)',
		'max_attach_lbl' => 'Max velikost pøílohy (v kb)',
		'usrsAD_lbl' => 'Uivatelé A-D',
		'usrsEH_lbl' => 'Uivatelé E-H',
		'usrsIL_lbl' => 'Uivatelé I-L',
		'usrsMP_lbl' => 'Uivatelé M-P',
		'usrsQT_lbl' => 'Uivatelé Q-T',
		'usrsUZ_lbl' => 'Uivatelé U-Z',
		'add_fgrp' => 'Pøidat skupinu fóra',
		'del_fgrp' => 'Vymazat skupinu fóra',
		'mod_fgrp' => 'Upravit skupinu fóra',
		'add_conf' => 'Pøidat konferenci',
		'del_conf' => 'Vymazat konferenci',
		'mod_conf' => 'Upravit konferenci',
		'add_cat' => 'Pøidat kategorii',
		'del_cat' => 'Vymazat kategorii',
		'mod_cat' => 'Upravit kategorii',
		'cat_title_hdr' => 'Prosím zadejte název (povinnı):',
		'cat_title_lbl' => 'Název:',
		'cat_hide_lbl' => 'Skrıt:',
		'cat_grps_lbl' => 'Privilegovaná skupina s pøístupem do této kategorie a jejích dceøinnıch konferencí:',
		'cat_desc_lbl' => 'Popis kategorie:',
		'cat_hide_hdr' => 'Zaškrtnìte pro skrytí této kategorie:',
		'cat_desc_hdr' => 'Zadejte popis této kategorie:',
		'cat_grps_hdr' => 'Pøístup do kategorie (volitelnì):',
		'cat_fgaccess_lbl' => 'Skupiny fóra, které mohou pøistupovat do této kategorie a jejích dceøinnıch konferencí:',
		'cnf_hide_hdr' => 'Skrıt:',
		'cnf_cat_hdr' => 'Zvolte kategorii, do které tato konference patøí:',
		'cnf_title_hdr' => 'Zadejte název této konference:',
		'cnf_desc_hdr' => 'Zadejte popis této konference:',
		'cnf_publ_r_hdr' => 'Zaškrtnutím tohoto políèka povolíte pøístup pro ètení anonymním uivatelùm:',
		'cnf_publ_w_hdr' => 'Zaškrtnutím tohoto políèka povolíte anonymním uivatelùm pøístup pro zápis:',
		'cnf_fgaccess_hdr' => 'Skupiny fóra, které mají pøístup do této konference:',
		'cnf_fgattach_hdr' => 'Skupiny fóra, které smí pøikládat k pøíspìvkùm pøílohy:',
		'cnf_usrs_hdr' => 'Uivatelé povìøení moderováním této konference:',
		'cnf_hide_lbl' => 'Zaškrtnutím tuto konferenci skryjete:',
		'cnf_cat_lbl' => 'Kategorie',
		'cnf_title_lbl' => 'Název konference',
		'cnf_desc_lbl' => 'Popis konference',
		'cnf_publ_r_lbl' => 'Anonymní pøístup pro ètení<br />[Pokud zaškrtnete tuto volbu, budou nepøihlášení uivatelé moci èíst zprávy v této konferenci.]',
		'cnf_publ_w_lbl' => 'Anonymní pøístup pro zápis<br />[Pokud zaškrtnete tuto volbu, budou nepøihlášení uivatelé moci vkládat nové zprávy do této konference.]',
		'cnf_fgaccess_lbl' => 'Skupina fóra s pøístupem pro ètení / zápis',
		'cnf_fgattach_lbl' => 'Skupina fóra s pøístupem pro zasílání pøíloh',
		'cnf_user_edit_hdr' => 'Úprava pøíspìvkù:',
		'cnf_user_edit_lbl' => 'Povolit uivatelùm upravovat vlastní pøíspìvky?',
		'fgrp_hide_lbl' => 'Skrıt:',
		'fgrp_title_lbl' => 'Název:',
		'fgrp_desc_lbl' => 'Popis skupiny fóra:',
		'fgrp_grps_lbl' => 'Privilegované skupiny:',
		'fgrp_hide_hdr' => 'Zaškrtnutím skryjete tuto skupinu:',
		'fgrp_title_hdr' => 'Prosím zadejte název (povinnı):',
		'fgrp_desc_hdr' => 'Zadejte popis této skupiny:',
		'fgrp_grps_hdr' => 'Aby mohli patøit do této skupiny fóra, musí uivatelé patøit do VŠECH zvolenıch skupin:',
		'fgrp_usrs_hdr' => 'Konkrétní privilegovaní uivatelé, kteøí také patøí do této skupiny fóra:',
		'db_clean' => 'Vyprázdnit tabulky fóra',
		'db_clean_note' => 'Jestlie kliknete na Odeslat, tato funkce projde celé chc forum a pokusí se najít jakékoli záznamy, které jsou vymazané nebo jim chybí nadøazenı záznam. Tato funkce se spouští, kdykoli je v tomto modulu vymazána konference nebo téma. Konkrétnì dìlá toto:<br />
(1) Vymae všechna témata, která nemají nadøazenou konferenci<br />
(2) Vymae všechny pøíspìvky, které nemají nadøazené téma nebo nadøazenou konferenci<br />
(3) Vymae kadı záznam formuláøe, kde vymazáno = 0 a<br />
(4) Vymae všechny záznamy v tabulce post_read (sledování novıch pøíspìvkù) odkazující na vymazanı pøíspìvek<br />
(5) Vymae všechny pøíspìvky, které jsou starší ne nastavená maximální doba pro mazání, která se nastavuje na stránce "konfigurace fóra"<br />',
		'no_recs' => 'ÁDNÉ ZÁZNAMY!',
		'what_to_do_hdr' => 'co chcete udìlat?',
		'submit' => 'odeslat',
		'cancel' => 'zrušit',
		'instructions' => 'Nebyly vytvoøeny ádné plug-iny fóra.
Ne budete moci pouívat tento nástroj, musíte provést základní nastavení fóra. Pokyny najdete v manuálu. Pokud ale
pøíliš spìcháte a nemáte èas èíst manuál, zaènìte tìmito kroky:<br /><br />
1. Kliknìte na název stránky, kam chcete fórum ve struktuøe stránek umístit.<br />
2. Kliknìte na modul stránky. Kliknìte na ikonu nového záznamu v modulu stránky.
3. Kliknìte na "chc forum" v seznamu plug-inù.<br />
4. Nastavte PID (ID stránky, které zjistíte podrením kurzoru myši nad ikonou stránky ve stromu stránek) adresáøe, kterı obsahuje vaše privilegované uivatele.<br />
v poli "PID adresáøe privilegovanıch uivatelù" ve flexformuláøi fóra.<br />
5. Nastavte pole "vıchozí bod" (pod flexformuláøem) na stránku nebo systémovı adresáø, kde budou uloeny záznamy vašeho fóra.<br />
6. Kliknìte na záloku Vzhled a pojmenujte fórum zadáním názvu do pole "název fóra".<br />
7. Kliknìte na záloku Bezpeènost. Zadejte do pøíslušného pole tajné slovo --
mùe to bıt jakékoliv slovo, fórum ho pouívá ke generování bezpeènostních klíèù.<br />
8. Ulote záznam plug-inu kliknutím na ikonu disku v horní èásti rámce.<br />
9. To je vše -- jste hotovi! Pokud chcete, mùete nyní pouít zadní modul fóra pro vytvoøení záznamù fóra (nìkteøí uivatelé to povaují za jednodušší).<br />',
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'msg_forum_select' => 'Valitse foorumi jonka tietoja haluat muokata',
		'msg_selection_select' => 'Valitse vaihtoehto alasveto-valikosta',
		'title' => 'CHC Foorumin hallinta',
		'ad_cats' => 'Muokkaa luokkia',
		'ad_confs' => 'Muokkaa keskusteluja',
		'ad_fgroups' => 'Muokkaa foorumin ryhmiä',
		'f_conf' => 'Konfiguroi foorumi',
		'addcat' => 'Lisää luokka',
		'modcat' => 'Muokkaa luokkaa',
		'delcat' => 'Poista luokka',
		'addconf' => 'Lisää keskustelu',
		'modconf' => 'Muokkaa keskustelua',
		'delconf' => 'Poista keskustelu',
		'addfgrp' => 'Lisää foorumin ryhmä',
		'modfgrp' => 'Muokkaa foorumin ryhmää',
		'delfgrp' => 'Poista foorumin ryhmä',
		'message_posts_del' => 'Seuraavat POSTS (uid / subject) (viestit (uid / aihe)) poistettiin pysyvästi koska niillä ei ollut isäntäkonfrenssia ja/tai viestijonoa :',
		'message_posts_prune_del' => 'Seuraavat POSTS (uid / subject) (viestit (uid / aihe)) poistettiin pysyvästi koska niiden vanhenemisikä oli ylittynyt:',
		'message_threads_del' => 'Seuraavat  THREADS (uid / subject) (viestijonot (uid / aihe)) poistettiin pysyvästi koska niillä ei ollut isäntäkonfrenssia :',
		'message_del' => 'DB puhdistaja kävi lävitse kaikki chc_forum taulut ja poisti kaikki tietueet joissa deleted = 1. Yhteensä poistettiin tietueita :',
		'message_del_lbl' => 'Poistetut viestit:',
		'message_pr_del' => 'DB puhdistaja puhdisti myös posts_read taulun, jossa säilytetään tiedot käyttäjien lukemista viesteistä. Kaikki tiedot jotka viittasivat viesteihin joita ei enää ole olemassa poistettiin.',
		'message_none' => 'Ei mitään!',
		'message_add_success' => 'Tietue onnistuneesti lisätty !',
		'message_del_success' => 'Tietue onnistuneesti poistettu !',
		'message_mod_success' => 'Tietue onnistuneesti muokattu !',
		'message_fconf_success' => 'Muutoksesi foorumin konfiguratioon onnistuneesti tallennettu !',
		'mailer_forum_url_lbl' => 'Anna sivustosi URL. Älä unohda lopun kauttaviivaa.Esim. http://omadomainisi.fi/',
		'mailer_disable_lbl' => 'Merkkaa tämä boxi estääksesi postituslista ominaisuudet:',
		'tmpl_path_lbl' => 'Polku muotoiltuihin forumin mallinteisiin.<br /><br />Tämän tulee olla relatiivinen polkuTypo3 installaatiosi juureen. Jätätyhjäksi jos käytätforumin oletus mallinteita.<br /><br />Esimerkki: fileadmin/forum_templates/',
		'allowed_file_types_lbl' => 'Pilkuin eroteltu lista liitteeseen hyväksyttävistä tiedosto-tyypeistä.<br /><br />Varoitus: Älä salli php tai html tiedostoja liitteiksi. Jos tee näin antaudut suurelle turvallisuus riskille koska kaikki nämä voidaan suorittaa suoraan selaimessa ohjelmina.<br /><br />Esimerkki: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'Pilkuin eroteltu lista liitteeseen hyväksyttävistä mime-tyypeistä.<br /><br />Esimerkki: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Suurin käyttäjän kuvan koko latauksessa (kb):',
		'max_attach_lbl' => 'Suurin liitteen koko (kb):',
		'usrsAD_lbl' => 'Käyttäjät A-D',
		'usrsEH_lbl' => 'Käyttäjät E-H',
		'usrsIL_lbl' => 'Käyttäjät I-L',
		'usrsMP_lbl' => 'Käyttäjät M-P',
		'usrsQT_lbl' => 'Käyttäjät Q-T',
		'usrsUZ_lbl' => 'Käyttäjät U-Ö',
		'add_fgrp' => 'Lisää foorumin ryhmä',
		'del_fgrp' => 'Poista foorumin ryhmä',
		'mod_fgrp' => 'Muokkaa foorumin ryhmää',
		'add_conf' => 'Lisää keskustelu',
		'del_conf' => 'Poista keskustelu',
		'mod_conf' => 'Muokkaa keskustelua',
		'add_cat' => 'Lisää luokka',
		'del_cat' => 'Poista luokka',
		'mod_cat' => 'Muokkaa luokkaa',
		'cat_title_hdr' => 'Anna otsikko (pakollinen)',
		'cat_title_lbl' => 'Otsikko:',
		'cat_hide_lbl' => 'Kätke:',
		'cat_grps_lbl' => 'Edustakäyttäjien ryhmät:',
		'cat_desc_lbl' => 'Luokan kuvaus:',
		'cat_hide_hdr' => 'Merkkaa jos haluat piilottaa tämän luokan:',
		'cat_desc_hdr' => 'Anna kuvaus tälle luokalle:',
		'cat_grps_hdr' => 'Luokan oikeudet (valinnainen):',
		'cat_fgaccess_lbl' => 'Forumin ryhmät joilla on oikeudet tähän luokkaan ja sen alakonfrensseihin:',
		'cnf_hide_hdr' => 'Kätke:',
		'cnf_cat_hdr' => 'Valitse luokka johon tämä keskustelu kuuluu:',
		'cnf_title_hdr' => 'Anna tämän keskustelun nimi:',
		'cnf_desc_hdr' => 'Anna kuvaus tälle keskustelulle:',
		'cnf_publ_r_hdr' => 'Merkkaa tämä boxi salliaksesi lukuoikeuden anonyymeille käyttäjille:',
		'cnf_publ_w_hdr' => 'Merkkaa tämä boxi salliaksesi postitusoikeuden anonyymeille käyttäjille:',
		'cnf_fgaccess_hdr' => 'Foorumin ryhmät joilla on oikeudet tähän keskusteluun:',
		'cnf_fgattach_hdr' => 'Foorumin ryhmät joilla on oikeus liittää tiedostoja viesteihin:',
		'cnf_usrs_hdr' => 'Käyttäjät jotka toimivat moderaattoreina tähän keskusteluun:',
		'cnf_hide_lbl' => 'Merkkaa tästä kätkeäksesi tämän keskustelun:',
		'cnf_cat_lbl' => 'Liokka',
		'cnf_title_lbl' => 'Keskustelun nimi',
		'cnf_desc_lbl' => 'Keskustelun kuvaus',
		'cnf_publ_r_lbl' => 'Anonyymi lukuoikeus<br />[Jos merkkaat tämän, vieras (joka ei ole sisäänkirjoittautunut) voi lukea kaikki tämän konfrenssin viestit.]',
		'cnf_publ_w_lbl' => 'Anonyymi postitusoikeus<br />[Jos merkkaat tämän, vieras (joka ei ole sisäänkirjoittautunut) voi lähettäää uusia viestejä tähän konfrenssiin.]',
		'cnf_fgaccess_lbl' => 'Foorumin ryhmän luku / kirjoitusoikeudet',
		'cnf_fgattach_lbl' => 'Foorumin ryhmän liitetiedosto-oikeudet',
		'cnf_user_edit_hdr' => 'Postin muokkaus:',
		'cnf_user_edit_lbl' => 'Salli käyttäjien muokata postiaan ?',
		'fgrp_hide_lbl' => 'Piilota:',
		'fgrp_title_lbl' => 'Otsikko:',
		'fgrp_desc_lbl' => 'Foorumin ryhmän kuvaus:',
		'fgrp_grps_lbl' => 'Edustakäyttäjien ryhmät:',
		'fgrp_hide_hdr' => 'Merkkaa tästä piilottaaksesi tämän ryhmän:',
		'fgrp_title_hdr' => 'Anna otsikko (pakollinen):',
		'fgrp_desc_hdr' => 'Anna kuvaus tälleryhmälle:',
		'fgrp_grps_hdr' => 'Kuuluakseen tähän foorumin ryhmään, tulee käyttäjien kuulua KAIKKIIN valittuihin ryhmiin:',
		'fgrp_usrs_hdr' => 'Erityiset edustakäyttäjät, jotka kuuluvat myös tähän foorumin ryhmään:',
		'db_clean' => 'Puhdista foorumin taulut',
		'db_clean_note' => 'KÄYTÄ TOIMINTAA VAROEN.  Tätä ei ole käännetty jotta varmasti ymmärrät mitä teet !!! Älä käytä jos et ymmärrä !!!<br />


If you press submit, this function will comb through the chc forum tables and attempt to repair any records that are either deleted or are missing a parent record. This function runs when ever a conference or thread is deleted in this module. More specifically, it does the following:<br />


(1) Deletes all threads that are missing a parent conference<br />


(2) Deletes all posts that are missing a parent thread or a parent conference<br />


(3) Deletes every form record where deleted = 0 and<br />


(4) Deletes all records in the post_read table (new post tracking) refering to a deleted post<br />',
		'no_recs' => 'EI TIETOJA!',
		'what_to_do_hdr' => 'mitä haluat tehdä ?',
		'submit' => 'tallenna',
		'cancel' => 'peruuta',
		'instructions' => 'Forum pluginia ei ole otettu käyttöön.
Ennenkuin voit käytää tätä työkalua Sinun tulee tehdä perusasetukset keskustelufoorumille.
Tehdäksesi tämän lue ensin manuaali. Jos et kuitenkaan kiireessäsi ehdi tätä tehdä, toimi käyttäen 
seuraavia askeIia päästäksesi alkuun
:<br /><br />
1. Klikkaa sivun otsikkoa sivustorakenteesta, jolle haluat asentaa foorumin.<br />
2. Klikkaa sivu modulia. Klikkaa uusi tietie ikoniasivu modulissa.<br />
3. Klikkaa "chc forum" pluginien listalta.<br />
4. Aseta PID (sivu ID, jonka löydät viemällä kursorin sivu ikonin päälle sivustorakenteessa) hakemistosta joka sisältää edustakäyttäjien tiedot.<br />
5. Aseta "aloituskohta" tieto (flexformin alla) sivulle ja järjestelmä hakemistoon (sysfolder)
jonne haluat tallettaa foorumin tiedot.<br />
6. Klikkaa ulkoasu tabia ja anna nimi foorumille kirjoittamalla se
"forumin otsikko" tietoon.<br />
7. Klikkaa turvallisuus tabia. anna salainen sana vastaavaan tietoon  --
sana voi olla mikä tahansa;  foorumi käyttää tätä tietoa generoidessaan turvallisuus  tunnuksia.<br />
8. Tallenna pluginin tiedot klikkaamalla levy ikonia sivun ylä laidassa.<br />
9. Se on siinä -- olet valmis! Halutessasi voit nyt taustalla luoda tietoja foorumiin käyttäen tasutan foorumi modulia (jotkut käyttäjät pitävät tätä helpompana).<br />',
	),
	'tr' => Array (
	),
	'se' => Array (
		'msg_forum_select' => 'Välj det forum du vill administrera:',
		'msg_selection_select' => 'Välj ett alternativ från nedrullningsmenyn',
		'title' => 'CHC forum-administration',
		'ad_cats' => 'Hantera kategorier',
		'ad_confs' => 'Hantera konferenser',
		'ad_fgroups' => 'Hantera grupper',
		'f_conf' => 'Konfigurera forum',
		'addcat' => 'Lägg till kategori',
		'modcat' => 'Ändra kategori',
		'delcat' => 'Radera kategori',
		'addconf' => 'Lägg till konferens',
		'modconf' => 'Ändra konferens',
		'delconf' => 'Radera konferens',
		'addfgrp' => 'Lägg till grupp',
		'modfgrp' => 'Ändra grupp',
		'delfgrp' => 'Radera grupp',
		'message_posts_del' => 'Följande INLÄGG (uid/ämne) har raderats permanent för att de inte tillhörde någon konferens eller ämne:',
		'message_posts_prune_del' => 'Följande INLÄGG (uid/ämne) har raderats permanent för att de blev för gamla:',
		'message_threads_del' => 'Följande ÄMNEN (uid/rubrik) har raderats permanent för att de endera saknade en huvudkonferens eller för att de inte innehöll några inlägg:',
		'message_del' => 'DB putsaren skannade alla tabeller i chc_forum och raderade all data som markerats med radera = 1. Totalt raderades följande antal data:',
		'message_del_lbl' => 'Raderade inlägg:',
		'message_pr_del' => 'DB putsaren putsade också upp posts_read-tabellen, som håller ordning på vilka inlägg de olika användarna läst. Alla inlägg för vilka en motsvarande postning inte längre existerar blev raderade.',
		'message_none' => 'Inga!',
		'message_add_success' => 'Datan lades till med framgång!',
		'message_del_success' => 'Datan raderades med framgång!',
		'message_mod_success' => 'Datan ändrades med framgång!',
		'message_fconf_success' => 'Dina ändringar till forumets konfiguration har sparats!',
		'mailer_forum_url_lbl' => 'Fyll i URLen till din hemsida. Kom ihåg snedstrecket i slutet!<br />Exempel: http://dindomain.com/',
		'mailer_disable_lbl' => 'Kryssa i denna ruta för att stänga postningslistans egenskaper.',
		'tmpl_path_lbl' => 'Sökväg till egen forummodell:<br /><br />Det här är en relativ sökväg från roten av din typo3-installation. Lämna tomt om du använder standardmodeller för forumet.<br /><br />Exempel: fileadmin/forum_modell/',
		'allowed_file_types_lbl' => 'Lista över godkända filtyper i bilagor, separerade med kommatecken<br /><br />VARNING: Tillåt inte php eller html-filer. Gör du det utsätter du forumet för ett allvarligt säkerhetshot, eftersom dessa filer kan köras i en webläsare.<br /><br />Exempel: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'En komma-separerad lista på de mime-typer som godkäns för bilagor.<br /><br />Exempel: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Max storlek på användarbild (i kb):',
		'max_attach_lbl' => 'Max storlek på bifogad fil (i kb):',
		'usrsAD_lbl' => 'Användare A-D',
		'usrsEH_lbl' => 'Användare E-H',
		'usrsIL_lbl' => 'Användare I-L',
		'usrsMP_lbl' => 'Användare M-P',
		'usrsQT_lbl' => 'Användare Q-T',
		'usrsUZ_lbl' => 'Användare U-Z',
		'add_fgrp' => 'Lägg till en grupp i forumet',
		'del_fgrp' => 'Ta bort en grupp från forumet',
		'mod_fgrp' => 'Ändra en grupp i forumet',
		'add_conf' => 'Lägg till en konferens',
		'del_conf' => 'Ta bort en konferens',
		'mod_conf' => 'Ändra en konferens',
		'add_cat' => 'Lägg till en kategori',
		'del_cat' => 'Ta bort en kategori',
		'mod_cat' => 'Ändra en kategori',
		'cat_title_hdr' => 'Skriv en rubrik (obligatorisk):',
		'cat_title_lbl' => 'Rubrik:',
		'cat_hide_lbl' => 'Göm:',
		'cat_grps_lbl' => 'FE grupp som har tillgång till denna katagori och underkategorier:',
		'cat_desc_lbl' => 'Kategoriförklaring:',
		'cat_hide_hdr' => 'Kryssa i för att gömma denna kategori:',
		'cat_desc_hdr' => 'Fyll i en förklaring för denna kategori:',
		'cat_grps_hdr' => 'Kategoriaccess (optional):',
		'cat_fgaccess_lbl' => 'Forum-grupper som har tillgång till denna kategori och underkategorier:',
		'cnf_hide_hdr' => 'Göm:',
		'cnf_cat_hdr' => 'Välj kategori som denna konferens hör till:',
		'cnf_title_hdr' => 'Fyll i konferensens namn:',
		'cnf_desc_hdr' => 'Fyll i en förklaring för konferensen:',
		'cnf_publ_r_hdr' => 'Kryssa i denna ruta för läsrättigheter för anonyma användare:',
		'cnf_publ_w_hdr' => 'Kryssa i denna ruta för att ge anonyma användare rätt att skicka inlägg:',
		'cnf_fgaccess_hdr' => 'Forum-grupper som har rätt att delta i denna konferens:',
		'cnf_fgattach_hdr' => 'Forum-grupper som har rätt att skicka bilagor med sina inlägg:',
		'cnf_usrs_hdr' => 'Användare som kan göra ändringar i denna konferens:',
		'cnf_hide_lbl' => 'Kryssa i för att gömma denna konferens.',
		'cnf_cat_lbl' => 'Kategori',
		'cnf_title_lbl' => 'Konferensens namn',
		'cnf_desc_lbl' => 'Konferensens förklaring',
		'cnf_publ_r_lbl' => 'Anonym läsrättighet<br />[Om du kryssar för denna kan gäster, som inte loggat in, läsa inlägg i denna konferens]',
		'cnf_publ_w_lbl' => 'Anonym inläggsrättighet<br />[Om du kryssar för denna kan gäster, som inte loggat in, skicka inlägg till denna konferens]',
		'cnf_fgaccess_lbl' => 'Forum-grupps läs/skicka rättighet',
		'cnf_fgattach_lbl' => 'Forum-grupps rättighet till bilagor',
		'cnf_user_edit_hdr' => 'Ändra inlägg:',
		'cnf_user_edit_lbl' => 'Tillåt användare att ändra sina egna inlägg?',
		'fgrp_hide_lbl' => 'Göm:',
		'fgrp_title_lbl' => 'Rubrik:',
		'fgrp_desc_lbl' => 'Forum-grupp definition:',
		'fgrp_grps_lbl' => 'Frontend grupper',
		'fgrp_hide_hdr' => 'Kryssa i för att gömma denna grupp:',
		'fgrp_title_hdr' => 'Fyll i en rubrik (obligatorisk):',
		'fgrp_desc_hdr' => 'Fyll i en förklaring för denna grupp:',
		'fgrp_grps_hdr' => 'För att höra till denna forum-grupp måste användaren höra till ALLA valda grupper:',
		'fgrp_usrs_hdr' => 'Speciella FE-användare som också hör till denna forum-grupp:',
		'db_clean' => 'Städa forumtabeller',
		'db_clean_note' => 'När du klickar på sänd kommer denna funktion att söka igenom tabellerna i chc-forumet och försöka reparera all den data som endera är raderad eller som saknar huvuddata. Denna funktion kör alltid då en konferens eller ett ämne är raderat från denna modul. I detalj görs följande:<br />
(1) Tar bort alla ämnen som saknar en huvudkonferens<br />
(2) Tar bort alla inlägg som saknar ett huvudämne eller en huvudkonferens<br />
(3) Tar bort all formulärdata där deleted = 0 och <br />
(4) Tar bort all data i post_read tabellen (ny inläggssökning) som refererar till ett borttaget inlägg<br />
(5) Tar bort alla inlägg som är äldre än den ålder som konfigurerats på "forum konfiguration"-sidan<br />',
		'no_recs' => 'INGEN DATA!',
		'what_to_do_hdr' => 'Vad vill du göra?',
		'submit' => 'skicka',
		'cancel' => 'avbryt',
		'instructions' => 'Det har inte skapats något för forum-pluginet.
Före du kan använda detta verktyg måste du göra en basinställning för forumet. Hur det görs kan du läsa om i manualen. Om du trots allt har för brått för att läsa manualen, ger vi här några korta steg i hur du kommer igång:<br /><br />
1. Klicka i sidlistan på rubriken på den sida som skall innehålla forumet.<br />
2. Klicka på Sid-modulen. Klicka på nytt element i sidmodulen.<br />
3. Klicka på "chc-forum" i listan över plugins.<br />
4. Ange PID (ID-nummer för sidan, numret syns när du för kursorn över sidikonen i sidlistan) för mappen där listan över FE-användare finns.<br />
5. Ange "startpunkt" fältet (under flexformuläret) för sidan eller sysfoldern där forumets data skalla lagras.<br />
6. Klicka på utseende-fliken och ange en rubrik som du skriver i fältet "Forumrubrik".<br />
7. Klicka på säkerhets-fliken. Fyll i ett hemligt ord i fältet -- dethär ordet kan vara vad som helst; forumet använder det för att skapa säkerhetskoder.<br />
8. Spara plugin-datan genom att klicka på diskikonen högst upp på sidan.<br />
9. Det var det -- Du är färdig! Om du vill kan du nu använda BE-forummodulerna för att skapa forumdata (endel användare tycker att det är lättare så).<br />',
	),
	'pt' => Array (
	),
	'ru' => Array (
		'msg_forum_select' => 'Ïîæàëóéñòà, âûáèğèòå ôîğóì äëÿ àäìèíèñòğèğîâàíèÿ:',
		'msg_selection_select' => 'Ïîæàëóéñòà, âûáåğèòå ïóíêò èç âûïàäàşùåãî ìåíş',
		'title' => 'Àäìèíèñòğèğîâàíèå CHC-ôîğóìà',
		'ad_cats' => 'Óïğàâëåíèå êàòåãîğèÿìè',
		'ad_confs' => 'Óïğàâëåíèå êîíôåğåíöèÿìè',
		'ad_fgroups' => 'Óïğàâëåíèå ãğóïïàìè ôîğóìà',
		'f_conf' => 'Êîíôèãóğàöèÿ ôîğóìà',
		'addcat' => 'Äîáàâèòü êàòåãîğèş',
		'modcat' => 'Èçìåíèòü êàòåãîğèş',
		'delcat' => 'Óäàëèòü êàòåãîğèş',
		'addconf' => 'Äîáàâèòü êîíôåğåíöèş',
		'modconf' => 'Èçìåíèòü êîíôåğåíöèş',
		'delconf' => 'Óäàëèòü êîíôåğåíöèş',
		'addfgrp' => 'Äîáàâèòü ãğóïïó ôîğóìà',
		'modfgrp' => 'Èçìåíèòü  ãğóïïó ôîğóìà',
		'delfgrp' => 'Óäàëèòü ãğóïïó ôîğóìà',
		'message_posts_del' => 'Ñëåäóşùèå ñîîáùåíèÿ (uid / çàãîëîâîê) áûëè óäàëåíû, ò.ê. äëÿ íèõ îòñóòñòâóåò ğîäèòåëüñêàÿ êîíôåğåíöèÿ è/èëè òåìà:',
		'message_posts_prune_del' => 'Ñëåäóşùèå ñîîáùåíèÿ (uid / çàãîëîâîê) áûëè óäàëåíû, ò.ê. äëÿ íèõ ïğåâûøåí ñğîê äàâíîñòè:',
		'message_threads_del' => 'Ñëåäóşùèå ÒÅÌÛ (uid / çàãîëîâîê) áûëè óäàëåíû, ò.ê. äëÿ íèõ îòñóòñòâóåò ğîäèòåëüñêàÿ êîíôåğåíöèÿ èëè â íèõ íå áûëî íèêàêèõ ñîîáùåíèé:',
		'message_del' => 'Ğåâèçîğ ÁÄ ïğîñìîòğåë âñå òàáëèöû chc-ôîğóìà, è óäàëèë âñå çàïèñè, ïîìå÷åííûå äëÿ óäàëåíèÿ (deleted = 1). Âåãî áûëî óäàëåíî ñëåäóşùåå ÷èñëî çàïèñåé:',
		'message_del_lbl' => 'Óäàëåííûå ñîîáùåíèÿ:',
		'message_pr_del' => 'Ğåâèçîğ ÁÄ òàêæå î÷èñòèë òàáëèöó posts_read, êîòîğàÿ õğàíèò çàïèñè î òîì, êàêèå ñîîáùåíèÿ ïğî÷èòàíû ïîëüçîâàòåëåì. Âñå ñòğîêè, äëÿ êîòîğûõ íåò ñîîòâåòñâóşùåãî ñîîáùåíèÿ áûëè óäàëåíû.',
		'message_none' => 'Íåò!',
		'message_add_success' => 'Çàïèñü óñïåøíî äîáàâëåíà!',
		'message_del_success' => 'Çàïèñü óñïåøíî óäàëåíà!',
		'message_mod_success' => 'Çàïèñü óñïåøíî èçìåíåíà!',
		'message_fconf_success' => 'Âàøè èçìåíåíèÿ â êîíôèãóğàöèè ôîğóìà ñîõğàíåíû!',
		'mailer_forum_url_lbl' => 'Ââåäèòå URL Âàøåãî ñàéòà. Íå çàáóäüòå çàêğûâàşùèé ñëıø!<br /><br />Íàïğèìåğ: http://yourdomain.com/',
		'mailer_disable_lbl' => 'Ïîñòàâüòå ãàëî÷êó, ÷òîáû âûêëş÷èòü ôóíêöèè ğàññûëêè.',
		'tmpl_path_lbl' => 'Ïóòü ê ïîëüçîâàòåëüñêèì øàáëîíàì ôîğóìà:<br /><br />Íåîáõîäèìî óêàçàòü ïóòü îòíîñèòåëüíî êîğíÿ âàøåé èíñòàëÿöèè Typo3. Îñòàâüòå ïóñòûì, åñëè âû èñïîëüçóåòå ñòàíäàğòíûå øàáëîíû ôîğóìà.<br /><br />Íàïğèìåğ: fileadmin/forum_templates/',
		'allowed_file_types_lbl' => 'Ğàçäåëåííûé çàïÿòûìè ñïèñîê ğàçğåøåííûõ òèïîâ ïğèñîåäèíÿåìûõ ôàéëîâ<br /><br />ÂÍÈÌÀÍÈÅ: Íå ğàçğåøàéòå ïğèñîåäèíÿòü ôàéëû php èëè html. Èíà÷å ñóùåñòâóåò âîçìîæíîñòü èõ çàïóñêà èç áğàóçåğà ïîëüçîâàòåëÿ, ÷òî áåçóñëîâíî ñíèæàåò óğîâåíü áåçîïàñíîñòè.<br /><br />Íàïğèìåğ: doc,gif,jpg,xls,ppt.',
		'allowed_mime_types_lbl' => 'Ğàçäåëåííûé çàïÿòûìè ñïèñîê ğàçğåøåííûõ  mime-òèïîâ ïğèñîåäèíÿåìûõ ôàéëîâ.<br /><br />Íàïğèìåğ: application/msword, image/gif, image/jpeg, application/excel, application/powerpoint',
		'max_user_img_lbl' => 'Ìàêñèìàëüíûé ğàçìåğ çàãğóæàåìîé êàğòèíêè (â kb)',
		'max_attach_lbl' => 'Ìàêñèìàëüíûé ğàçìåğ çàãğóæàåìîãî ôàéëà (â kb)',
		'usrsAD_lbl' => 'Ïîëüçîâàòåëè A-D',
		'usrsEH_lbl' => 'Ïîëüçîâàòåëè E-H',
		'usrsIL_lbl' => 'Ïîëüçîâàòåëè I-L',
		'usrsMP_lbl' => 'Ïîëüçîâàòåëè M-P',
		'usrsQT_lbl' => 'Ïîëüçîâàòåëè Q-T',
		'usrsUZ_lbl' => 'Ïîëüçîâàòåëè U-Z',
		'add_fgrp' => 'Äîáàâèòü ãğóïïó ôîğóìà',
		'del_fgrp' => 'Óäàëèòü ãğóïïó ôîğóìà',
		'mod_fgrp' => 'Èçìåíèòü ãğóïïó ôîğóìà',
		'add_conf' => 'Äîáàâèòü êîíôåğåíöèş',
		'del_conf' => 'Óäàëèòü êîíôåğåíöèş',
		'mod_conf' => 'Èçìåíèòü êîíôåğåíöèş',
		'add_cat' => 'Äîáàâèòü êàòåãîğèş',
		'del_cat' => 'Óäàëèòü êàòåãîğèş',
		'mod_cat' => 'Èçìåíèòü êàòåãîğèş',
		'cat_title_hdr' => 'Ïîæàëóéñòà, ââåäèòå çàãîëîâîê (îáÿçàòåëüíî):',
		'cat_title_lbl' => 'Çàãîëîâîê :',
		'cat_hide_lbl' => 'Ñïğÿòàòü:',
		'cat_grps_lbl' => 'Ãğóïïû âåá-ñàéòà:',
		'cat_desc_lbl' => 'Îïèñàíèå êàòåãîğèè:',
		'cat_hide_hdr' => 'Îòìåòüòå, ÷òîáû ñïğÿòàòü ıòó êàòåãîğèş:',
		'cat_desc_hdr' => 'Ââåäèòå îïèñàíèå êàòåãîğèè:',
		'cat_grps_hdr' => 'Ïğàâà äîñòóïà ê êàòåãîğèè (íåîáÿçâòåëüíî):',
		'cat_fgaccess_lbl' => 'Ãğóïïà ôîğóìà, èìåşùàÿ äîñòóï ê êàòåãîğèè è å¸ êîíôåğåíöèÿì',
		'cnf_hide_hdr' => 'Ñïğÿòàòü:',
		'cnf_cat_hdr' => 'Îòìåòüòå êàòåãîğèş, ê êîòîğîé ïğèíàäëåæèò ıòà êîíôåğåíöèÿ:',
		'cnf_title_hdr' => 'Ââåäèòå íàçâàíèå ıòîé êîíôåğåíöèè:',
		'cnf_desc_hdr' => 'Ââåäèòå îïèñàíèå ıòîé êîíôåğåíöèè:',
		'cnf_publ_r_hdr' => 'Ïîñòàâüòå ãàëî÷êó ÷òîáû ğàçğåøèòü ÷òåíèå íåçàğåãèñòğèğîâàííûì ïîëüçîâàòåëÿì:',
		'cnf_publ_w_hdr' => 'Ïîñòàâüòå ãàëî÷êó ÷òîáû ğàçğåøèòü îñòàâëÿòü ñîîáùåíèÿ íåçàğåãèñòğèğîâàííûì ïîëüçîâàòåëÿì:',
		'cnf_fgaccess_hdr' => 'Ãğóïïû, êîòîğûì ğàçğåøåí äîñòóï ê ıòîé êîíôåğåíöèè:',
		'cnf_fgattach_hdr' => 'Ãğóïïû, êîòîğûì ğàçğåøåíî ïğèêğåïëÿòü ôàéëû ê ñîîáùåíèÿì:',
		'cnf_usrs_hdr' => 'Ïîëüçîâàòåëè, íàçíà÷åííûå ìîäåğàòîğàìè êîíôåğåíöèè:',
		'cnf_hide_lbl' => 'Ïîñòàâüòå ãàëî÷êó, ÷òîáû ñïğÿòàòü ıòó êîíôåğåíöèş:',
		'cnf_cat_lbl' => 'Êàòåãîğèÿ',
		'cnf_title_lbl' => 'Íàçâàíèå êîíôåğåíöèè',
		'cnf_desc_lbl' => 'Îïèñàíèå êîíôåğåíöèè',
		'cnf_publ_r_lbl' => '×òåíèå íåçàğåãèñòğèğîâàííûìè ïîëüçîâàòåëÿìè<br />[Åñëè îòìåòèòü çäåñü, òî ãîñòè ñìîãóò ÷èòàòü ñîîáùåíèÿ â ıòîé êîíôåğåíöèè.]',
		'cnf_publ_w_lbl' => 'Ğàçìåùåíèå ñîîáùåíèé íåçàğåãèñòğèğîâàííûìè ïîëüçîâàòåëÿìè<br />[Åñëè îòìåòèòü çäåñü, òî ãîñòè ñìîãóò îñòàâëÿòü ñîîáùåíèÿ â ıòîé êîíôåğåíöèè..]',
		'cnf_fgaccess_lbl' => 'Ãğóïïà ñ ïğàâàìè ÷òåíèÿ è îòïğàâêè ñîîáùåíèé',
		'cnf_fgattach_lbl' => 'Ãğóïïà ñ ïğàâàìè ïğèñîåäèíåíèÿ ôàéëîâ',
		'cnf_user_edit_hdr' => 'Ğåäàêòèğîâàíèå ñîîáùåíèÿ:',
		'cnf_user_edit_lbl' => 'Ğàçğåøèòü ïîëüçîâàòåëÿì ğåäàêòèğîâàòü èõ ñîáñòâåííûå ñîîáùåíèÿ?',
		'fgrp_hide_lbl' => 'Ñïğÿòàòü:',
		'fgrp_title_lbl' => 'Çàãîëîâîê :',
		'fgrp_desc_lbl' => 'Îïèñàíèå ãğóïïû ôîğóìà:',
		'fgrp_grps_lbl' => 'Ãğóïïû âåá-ñàéòà:',
		'fgrp_hide_hdr' => 'Ïîìåòüòå, ÷òîáû ñïğÿòàòü ıòó ãğóïïó:',
		'fgrp_title_hdr' => 'Ïîæàëóéñòà, ââåäèòå çàãîëîâîê (îáÿçàòåëüíî):',
		'fgrp_desc_hdr' => 'Ââåäèòå îïèñàíèå ãğóïïû:',
		'fgrp_grps_hdr' => '×òîáû âõîäèòü â ıòó ãğóïïó ôîğóìà, ïîëüçîâàòåëè äîëæíû âõîäèòü âî ÂÑÅ îòìå÷åííûå ãğóïïû:',
		'fgrp_usrs_hdr' => 'Îòäåëüíûå ïîëüçîâàòåëè âåá-ñàéòà, òàêæå âõîäÿùèå â ıòó ãğóïïó ôîğóìà:',
		'db_clean' => 'Î÷èñòèòü òàáëèöû ôîğóìà',
		'db_clean_note' => 'Åñëè Âû íàæìåòå îòïğàâèòü (submit), ıòà ôóíêöèÿ "ïğî÷åøåò" âñå òàáëèöû ÁÄ chc-ôîğóìà è ïîïûòàåòñÿ âîññòàíîâèòü çàïèñè, êîòîğûå ëèáî áûëè óäàëåíû, ëèáî äëÿ êîòîğûõ íåò ñîîòâåòñâóşùåé ğîäèòåëüñêîé çàïèñè. İòà ôóíêöèÿ çàïóñêàåòñÿ òîãäà, êîãäà èç ôîğóìà óäàëÿåòñÿ êîíôåğåíöèÿ èëè òåìà. À òî÷íåå, ïğîèñõîäèò ñëåäóşùåå:<br />
                                                        (1) Óäàëÿşòñÿ âñå òåìû, äëÿ êîòîğûõ íåò ğîäèòåëüñêîé êîíôåğåíöèè<br />
                                                        (2) Óäàëÿşòñÿ âñå ñîîáùåíèÿ, äëÿ êîòîğûõ íåò ğîäèòåëüñêîé òåìû èëè êîíôåğåíöèè<br />
                                                        (3) Óäàëÿşòñÿ çàïèñè, ãäå deleted = 0 è<br />
                                                        (4) Óäàëÿşòñÿ âñå çàïèñè â òàáëèöå post_read (æóğíàë íîâûõ ñîîáùåíèé) ññûëàşùèåñÿ íà óäàëåííûå ñîîáùåíèÿ<br />
                                                        (5) Óäàëÿşòñÿ âñå ñîîáùåíèÿ ñòàğøå "ñğîêà äàâíîñòè", êîòîğûé óñòàíîâëåí â ğàçäåëå "Êîíôèãóğöèÿ ôîğóìà"<br />',
		'no_recs' => 'ÍÅÒ ÇÀÏÈÑÅÉ!',
		'what_to_do_hdr' => '÷òî âû õîòèòå âûïîëíèòü?',
		'submit' => 'îòïğàâèòü',
		'cancel' => 'îòìåíèòü',
		'instructions' => 'Íå áûëî ñîçäàíî íè îäíîãî ıêçåìïëÿğà ôîğóìà. 
Ïåğåä òåì, êàê âû ñìîæåòå èñïîëüçîâàòü ıòîò èíñòğóìåíò íåîáõîäèìî
ïğîèçâåñòè áàçîâûå íàñòğîéêè ôîğóìà. Îáğàòèòåñü ê äîêóìåíòàöèè.
Îäíàêî, åñëè âû ñëèøêîì ñïåøèòå, ñëåäóşùèå øàãè ïîìîãóò âàì íà÷àòü:<br /><br />
1. Â äåğåâå ñàéòà êëèêíèòå íà çàãîëîâêå ñòğàíèöû, íà êîòîğîé õîòèòå ğàçìåñòèòü ôîğóì.<br />
2. Ïåğåéäèòå â ğåæèì "Ñòğàíèöà" è íàæìèòå èêîíêó "ñîçäàòü íîâóş çàïèñü".<br />
3. Âûáåğåòå CHC-Forum â ñïèñêå ğàñøèğåíèé.<br />
4. Óñòàíîâèòå PID ïàïêè ñ ïîëüçîâàòåëÿìè ñàéòà.<br />
5. Óñòàíîâèòå "Èñõîäíóş òî÷êó" - ñèñòåìíóş äèğåêòîğèş ñ çàïèñÿìè ôîğóìà.<br />
6. Êëèêíèòå íà çàêëàäêó "Âíåøíèé âèä" è ââåäèòå çàãîëîâîê ôîğóìà.<br />
7. Êëèêíèòå íà çàêëàäêó "Áåçîïàñíîñòü" è ââåäèòå ñåêğåòíîå ñëîâî. İòî ìîæåò áûòü êàêîå óãîäíî ñëîâî - ôîğóì èñïîëüçóåò åãî äëÿ ãåíåğàöèè õıøà.<br />
8. Ñîõğàíèòå çàïèñü íàæàòèåì íà èêîíêó ñ äèñêîì íàâåğõó ôğåéìà.<br />
9. Âîò è âñå - ìîæíî ğàáîòàòü! Åñëè õîòèòå, òî ìîæíî èñïîëüçîâàòü âíóòğåííèé ìîäóëü äëÿ ñîçäàíèÿ çàïèñåé íà ôîğóìå (íåêîòîğûå ñ÷èòàşò, ÷òî òàê ëåã÷å).<br />',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'msg_forum_select' => 'Odaberite forum koji elite administrirati:',
		'msg_selection_select' => 'Odaberite opciju iz padajuæeg izbornika',
		'title' => 'CHC forum administracija',
		'ad_cats' => 'Upravljanje kategorijama',
		'ad_confs' => 'Upravljanje temama',
		'ad_fgroups' => 'Upravljanje grupama',
		'f_conf' => 'Konfiguriranje foruma',
		'addcat' => 'Dodavanje kategorije',
		'modcat' => 'Izmjena kategorije',
		'delcat' => 'Brisanje kategorije',
		'addconf' => 'Dodavanje teme',
		'modconf' => 'Izmjena teme',
		'delconf' => 'Brisanje teme',
		'addfgrp' => 'Dodavanje grupe',
		'modfgrp' => 'Izmjena grupe',
		'delfgrp' => 'Brisanje grupe',
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
		'msg_forum_select' => '½Ğ¿ï¾Ü§A­nºŞ²zªº½×¾Â:',
		'msg_selection_select' => '½Ğ±q©Ô¤U¿ï³æ¤¤¿ï¾Ü¤@­Ó¿ï¶µ:',
		'title' => 'CHC½×¾ÂºŞ²z',
		'ad_cats' => 'ºŞ²z¤ÀÃş',
		'ad_confs' => 'ºŞ²z°Q½×°Ï',
		'ad_fgroups' => 'ºŞ²z½×¾Â¸s²Õ',
		'f_conf' => '³]©w½×¾Â',
		'addcat' => '·s¼W¤ÀÃş',
		'modcat' => '­×§ï¤ÀÃş',
		'delcat' => '§R°£¤ÀÃş',
		'addconf' => '·s¼W°Q½×°Ï',
		'modconf' => '­×§ï°Q½×°Ï',
		'delconf' => '§R°£°Q½×°Ï',
		'addfgrp' => '·s¼W½×¾Â¸s²Õ',
		'modfgrp' => '­×§ï½×¾Â¸s²Õ',
		'delfgrp' => '§R°£½×¾Â¸s²Õ',
		'message_posts_del' => '¥H¤Uªº¤å³¹(uid / ¥DÃD)³Q¥Ã»·§R°£, ¦]¬°¥¦­Ì¨S¦³©ÒÄİªº°Q½×°Ï¤Î/©Î³sÃ´:',
		'message_posts_prune_del' => '¥H¤Uªº¤å³¹(uid / ¥DÃD)³Q¥Ã»·§R°£, ¦]¬°¥¦­Ì¶W¹L¤F§R°£ªº­­´Á:',
		'message_threads_del' => '¥H¤Uªº³sÃ´ (uid / ¥DÃD)³Q¥Ã»·§R°£, ¦]¬°¥¦­Ì¨S¦³©ÒÄİªº°Q½×°Ï, ©Î¬O¨ä¤¤¨S¦³¤å³¹:',
		'message_del' => 'DB²M°£¾¹±½´y©Ò¦³chc_forumªí®æ, ¦Ó¥B§R°£©Ò¦³deleted = 1ªº°O¿ı¡CÁ`¦@§R°£¤F¥H¤U¼Æ¥Øªº°O¿ı:',
		'message_del_lbl' => '§R°£¤å³¹:',
		'message_pr_del' => 'DB²M°£¾¹¦P¼Ë²M°£post_readªí®æ, ³oªí®æ°O¿ı¨C¦W¨Ï¥ÎªÌ¤w¸gÅª¹Lªº¤å³¹¡C¥ô¦ó¨S¦³¬ÛÀ³¤å³¹¦s¦bªº°O¿ı³£·|³Q§R°£',
		'message_none' => '¨S¦³!',
		'message_add_success' => '·s¼W°O¿ı¦¨¥\\!',
		'message_del_success' => '§R°£°O¿ı¦¨¥\\!',
		'message_mod_success' => '­×§ï°O¿ı¦¨¥\\!',
		'message_fconf_success' => '§A¹ï½×¾Â³]©w©Ò§@ªº­×§ï¤v³QÀx¦s!',
		'mailer_forum_url_lbl' => '¿é¤J§Aºô¯¸ªºURL¡C¤£­n§Ñ¤F³Ì«áªº/!<br/><br/>¨Ò:http://yourdomain.com/',
		'mailer_disable_lbl' => '¿ï¾Ü³o²°¤l¥HÃö³¬¹q¶l¦W³æ(mailing list) ¥\\¯à',
		'tmpl_path_lbl' => '³]©w½×¾Â¼Ëª©ªº¸ô®|:<br/><br/>¦¹À³¬°¤@­Ó»Ptypo3®Ú¥Ø¿ı¬Û¹ïªº¸ô®|¡C«O«ùªÅ¥Õ¥H¨Ï¥Î¹w³]ªº¼Ëª©¡C<br/><br/>¨Ò:fileadmin/forum_templates/',
		'allowed_file_types_lbl' => '¥H³r¸¹¤À¶}ªº¥i§@ªş¥óªºÀÉ®×Ãş«¬ªº¦W³æ<br/><br/>Äµ§i:¤£­n®e³\\php©ÎhtmlÀÉ§@ªş¥ó¡C³o¼Ë°µ·|§Î¦¨ÄY­«ªº¦w¥ş©Ê­·ÀI, ¦]¬°©Ò¦³ªºªş¥ó³£¦³¥i¯à³Q·ÈÄı¾¹±Ò°Ê¡C<br/><br/>¨Ò:doc,gif,jpg,xls,ppt',
		'allowed_mime_types_lbl' => '¥H³r¸¹¤À¶}ªş¥óªºMIMEÃş«¬ªº¦W³æ<br/><br/>¨Ò:application/msword,image/gif,image/jpeg,application/excel,application/powerpoint',
		'max_user_img_lbl' => '¨Ï¥ÎªÌ¤W¸ü¹Ï¤ùªº³Ì¤j­È(kb)',
		'max_attach_lbl' => '³Ì¤jªºªş¥ó­È(kb)',
		'usrsAD_lbl' => '¨Ï¥ÎªÌA-D',
		'usrsEH_lbl' => '¨Ï¥ÎªÌE-H',
		'usrsIL_lbl' => '¨Ï¥ÎªÌI-L',
		'usrsMP_lbl' => '¨Ï¥ÎªÌM-P',
		'usrsQT_lbl' => '¨Ï¥ÎªÌQ-T',
		'usrsUZ_lbl' => '¨Ï¥ÎªÌU-Z',
		'add_fgrp' => '·s¼W½×¾Â¸s²Õ',
		'del_fgrp' => '§R°£½×¾Â¸s²Õ',
		'mod_fgrp' => '­×§ï½×¾Â¸s²Õ',
		'add_conf' => '·s¼W°Q½×°Ï',
		'del_conf' => '§R°£°Q½×°Ï',
		'mod_conf' => '­×§ï°Q½×°Ï',
		'add_cat' => '·s¼W¤ÀÃş',
		'del_cat' => '§R°£¤ÀÃş',
		'mod_cat' => '­×§ï¤ÀÃş',
		'cat_title_hdr' => '½×¿é¤J¥DÃD(¥²¶·):',
		'cat_title_lbl' => '¥DÃD:',
		'cat_hide_lbl' => 'ÁôÂÃ',
		'cat_grps_lbl' => '«e¥x¸s²Õ¥i¥H¦s¨ú³o­Ó¤ÀÃşÖÛ¨ä¤¤ªº°Q½×°Ï:',
		'cat_desc_lbl' => '¤ÀÃşÂ²¤¶:',
		'cat_hide_hdr' => '¿ï¾ÜÁôÂÃ¦¹¤ÀÃş:',
		'cat_desc_hdr' => '¿é¤J¦¹¤ÀÃşªºÂ²¤¶:',
		'cat_grps_hdr' => '¤ÀÃşÅv­­(¥i¿ï¾Ü):',
		'cat_fgaccess_lbl' => '¥i¦s¨ú¦¹¤ÀÃş©M¨ä¤¤°Q½×°Ïªº½×¾Â¸s²Õ:',
		'cnf_hide_hdr' => 'ÁôÂÃ:',
		'cnf_cat_hdr' => '¿ï¾Ü¦¹°Q½×°Ï©ÒÄİªº¤ÀÃş:',
		'cnf_title_hdr' => '¿é¤J¦¹°Q½×°Ïªº¦WºÙ:',
		'cnf_desc_hdr' => '¿é¤J¦¹°Q½×°ÏªºÂ²¤¶:',
		'cnf_publ_r_hdr' => '¿ï¾Ü¦¹²°¥Hµ¹¤©°Î¦W¨Ï¥ÎªÌÅªªºÅv­­:',
		'cnf_publ_w_hdr' => '¿ï¾Ü¦¹²°¥Hµ¹¤©°Î¦W¨Ï¥ÎªÌµn¿ı¤å³¹ªºÅv­­:',
		'cnf_fgaccess_hdr' => '¥i¥H¦s¨ú¦¹°Q½×°Ïªº½×¾Â¸s²Õ:',
		'cnf_fgattach_hdr' => '¥i¥H¦b¤å³¹ªş¥óªº½×¾Â¸s²Õ:',
		'cnf_usrs_hdr' => 'ºÊºŞ¦¹°Q½×°Ïªº«ü©w¨Ï¥ÎªÌ:',
		'cnf_hide_lbl' => '¿ï¾Ü¦¹²°¥HÁôÂÃ¦¹°Q½×°Ï',
		'cnf_cat_lbl' => '¤ÀÃş',
		'cnf_title_lbl' => '°Q½×°Ï¦WºÙ',
		'cnf_desc_lbl' => '°Q½×°ÏÂ²¤¶',
		'cnf_publ_r_lbl' => '°Î¦WªÌÅª¨úªºÅv­­<br/>[°²¦p§A¿ï¨ú³o¸Ì, ¨Ó»«(¨S¦³µn¤J)¨Ï¥ÎªÌ¥i¥H¦b¦¹°Q½×°ÏÅª¨ú¤å³¹]',
		'cnf_publ_w_lbl' => '°Î¦WªÌµn¿ı¤å³¹ªºÅv­­<br/>[°²¦p§A¿ï¨ú³o¸Ì, ¨Ó»«(¨S¦³µn¤J)¨Ï¥ÎªÌ¥i¥H¦b¦¹°Q½×°Ïµn¿ı·s¤å³¹]',
		'cnf_fgaccess_lbl' => '½×¾Â¸s²ÕÅª/µn¿ı¤å³¹ªºÅv­­',
		'cnf_fgattach_lbl' => '½×¾Â¸s²Õªş¥óªºÅv­­',
		'cnf_user_edit_hdr' => '­×§ï¤å³¹:',
		'cnf_user_edit_lbl' => '®e³\\¨Ï¥ÎªÌ­×§ï¦Û¤vªº¤å³¹¡H',
		'fgrp_hide_lbl' => 'ÁôÂÃ:',
		'fgrp_title_lbl' => '¥DÃD:',
		'fgrp_desc_lbl' => '½×¾Â¸s²ÕÂ²¤¶:',
		'fgrp_grps_lbl' => '«e¥x¸s²Õ:',
		'fgrp_hide_hdr' => '¿ï¨ú¦¹¥HÁôÂÃ¦¹¸s²Õ:',
		'fgrp_title_hdr' => '½Ğ¿é¤J¦WºÙ(¥²¶·):',
		'fgrp_desc_hdr' => '¿é¤J¦¹¸s²ÕªºÂ²¤¶:',
		'fgrp_grps_hdr' => 'Äİ©ó¦¹½×¾Â¸s²Õªº¨Ï¥ÎªÌ¤@©wÄİ©ó©Ò¦³³Q¿ï¾Üªº¸s²Õ:',
		'fgrp_usrs_hdr' => '¤@¨Ç«ü©w¤]Äİ©ó¦¹½×¾Â¸s²Õªº«e¥x¨Ï¥ÎªÌ:',
		'db_clean' => '²M°£½×¾Âªí®æ:',
		'db_clean_note' => '°²¦p§A«ö»¼¥æÁä¡A¦¹¥\\¯à·|§ä¹M¾ã­Óchc½×¾Âªí®æ©M¹Á¸Õ­×´_¥ô¦ó³Q§R°£©Î¥¢¥h¤W¼h°O¿ıªº°O¿ı¡C¤£½×¦ó®É¤@­Ó°Q½×°Ï©Î¦¹¥\\¯à¤å³¹¨t¦C¦b¼Ò²Õ¤¤³Q§R°£¡A¦¹¥\\¯à´N·|°õ¦æ¡C§ó·Ç½Tªº»¡¡A¥¦°µ¥H¤Uªº¨Æ¡G<br/>
(1) §R°£©Ò¦³¨S¦³¤W¼h°Q½×°Ïªº¤å³¹¨t¦C<br/>
(2) §R°£©Ò¦³¨S¦³¤W¼h³sµ²©Î°Q½×°Ïªº¤å³¹<br/>
(3) §R°£©Ò¦³ deleted =0 ªºªí®æ°O¿ı<br/>
(4) §R°£©Ò¦³¦bpost_readªí®æ(·s¤å³¹°l&#36394;)¤¤«ü¨ì¤@­Ó¤w§R°£¤å³¹ªº°O¿ı<br/>
(5) °£°£©Ò¦³¶W¥X§R°£´Á­­ªº¤å³¹¡A§R°£´Á­­¥i¦b¡u½×¾Â³]©w­¶¡v¤¤³]©w<br/>',
		'no_recs' => '¨S¦³°O¿ı¡I',
		'what_to_do_hdr' => '§A·Q°µ¬Æ»ò¡H',
		'submit' => '»¼¥æ',
		'cancel' => '¨ú®ø',
		'instructions' => '¨S¦³½×¾Â´¡¤J¦¡¤¸¥óªº¨Æ¶µ³Q«Ø¥ß¡C
¦b§A¥i¥H¥Î¦¹¤u¨ã¤§«e¡A§A»İ­n¬°½×¾Â§@°ò¥»ªº³]©w¡C¦ı¬O¡A¦pªG§A¤Ó»°¦£¡A¨S¦³®É¶¡¾\\Åª¨Ï¥ÎªÌ¤â¥U¡A³o¨Ç¨BÆJÀ³·|À°§U§A¶}©l¡G<br/><br/>
1. ÂIÀ»¦bºô­¶¾ğ¹Ï¤¤§A·QÀx¦s½×¾Âªººô­¶ªº¦WºÙ¡C<br/>
2. ÂIÀ»ºô­¶¼Ò²Õ¡CÂIÀ»¦bºô­¶¼Ò²Õ¤¤ªº·s°O¿ı¹Ï¥Ü¡C<br/>
3. ÂIÀ»´¡¤J¦¡¤¸¥ó¦W³æ¤¤ªº¡uCHC ½×¾Â¡v¡C<br/>
4. ¦b½×¾ÂªºFlexForm¤¤¡u«e¥x¨Ï¥ÎªÌÀx¦s¸ê®Æ§¨pid¡v¤@Äæ¤¤³]©w¥]§t«e¥x¨Ï¥ÎªÌªº¸ê®Æ§¨ªºPID (ºô­¶ID, ¥i¥H³z¹L§â·ÆÛW¹«©ñ¦bºô­¶¾ğ¹Ï¤¤ºô­¶ªº¹Ï¥Ü¤W±oª¾)¡C<br/>
5. ³]©w¡u°_©lÂI¡vÄæ (¦bflexform¤U­±)¬°ºô­¶©Î¨t²Î¸ê®Æ§¨¡A¨ä¤¤§A·|Àx¦s§Aªº½×¾Â°O¿ı
6. ÂIÀ»¥X²{ªº¤À­¶¡A¦b¡u½×¾Â¦WºÙ¡vÄæ¦ì¤¤¿é¤J§Aªº½×¾Âªº¦WºÙ¨Ó¬°§Aªº½×¾Â©R¦W<br/>
7. ÂIÀ»¦w¥ş©Ê¤À­¶¡C¦b¬ÛÀ³ªºÄæ¦ì¤¤¿é¤J¤@­Ó±K½X -- ³o­Ó±K½X¥i¥H¬O¥ô¦ó¤å¦r²Õ¦X: ½×¾Â¥H¦¹²£¥Í¦w¥ş¥[±K<br/>
8. ³z¹LÂIÀ»¤W¤èªººÏºĞ¹Ï¥ÜÀx¦s¤¸¥ó°O¿ı<br/>
9. ´N³o¼Ë -- ·d©w! ¦p§A³ßÅw, §A²{¦b¥i¥H¥Î«á¶Ô½×¾Â¼Ò²Õ¨Ó«Ø¥ß½×¾Â°O¿ı(¦³¨Ç¤H·|Ä±±o³o¼Ë°µ¤ñ¸û©ö)<br/>',
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>