<?php
/**
 * Language labels for plugin "tx_newloginbox_pi3"
 * 
 * TYPO3 CVS ID: $Id: locallang.php,v 1.1.1.1 2010/04/15 10:03:53 peimic.comprock Exp $
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'listFieldHeader_username' => 'Username:',
		'listFieldHeader_name' => 'Name:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Country:',
		'listFieldHeader_city' => 'City',
		'listFieldHeader_zip' => 'Zipcode',
		'listFieldHeader_telephone' => 'Telephone',
		'listFieldHeader_address' => 'Address',
		'listFieldHeader_title' => 'Title',
		'listFieldHeader_homepage' => 'Homepage',
		'listFieldHeader_company' => 'Company',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'What I wish to contribute:',
		'listFieldHeader_personallife' => 'My personal life:',
		'listFieldHeader_typo3experiences' => 'Experience:',
		'pi_list_browseresults_prev' => '< Previous',
		'pi_list_browseresults_next' => 'Next >',
		'pi_list_browseresults_displays' => 'Displaying users ###SPAN_BEGIN###%s to %s</span> out of ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Search',
		'singleview_created' => 'Created:',
		'singleview_lastLogin' => 'Last login:',
		'singleview_detailsAbout' => 'Details about',
		'singleview_limitedDetailsAbout' => 'Limited details about',
		'singleview_back' => 'Back',
	),
	'dk' => Array (
		'listFieldHeader_username' => 'Brugernavn:',
		'listFieldHeader_name' => 'Navn:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'By:',
		'listFieldHeader_zip' => 'Postnr:',
		'listFieldHeader_telephone' => 'Telefon:',
		'listFieldHeader_address' => 'Adresse:',
		'listFieldHeader_title' => 'Titel:',
		'listFieldHeader_homepage' => 'Hjemmeside:',
		'listFieldHeader_company' => 'Firma:',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Hvad jeg vil bidrage med:',
		'listFieldHeader_personallife' => 'Mit personlige liv:',
		'listFieldHeader_typo3experiences' => 'Erfaring:',
		'pi_list_browseresults_page' => 'Side',
		'pi_list_browseresults_prev' => '< Forrige',
		'pi_list_browseresults_next' => 'Nжste >',
		'pi_list_browseresults_displays' => 'Viser brugere ###SPAN_BEGIN###%s til %s</span> ud af ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Sшg',
		'singleview_created' => 'Oprettet:',
		'singleview_lastLogin' => 'Sidste login:',
		'singleview_detailsAbout' => 'Detaljer om',
		'singleview_limitedDetailsAbout' => 'Begrжnsede detaljer om',
		'singleview_back' => 'Tilbage',
	),
	'de' => Array (
		'listFieldHeader_username' => 'Benutzername:',
		'listFieldHeader_name' => 'Name:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'Stadt',
		'listFieldHeader_zip' => 'PLZ',
		'listFieldHeader_telephone' => 'Telefon',
		'listFieldHeader_address' => 'Adresse',
		'listFieldHeader_title' => 'Titel',
		'listFieldHeader_homepage' => 'Homepage',
		'listFieldHeader_company' => 'Firma',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Was ich beitragen mцchte:',
		'listFieldHeader_personallife' => 'Mein Leben:',
		'listFieldHeader_typo3experiences' => 'Erfahrung:',
		'pi_list_browseresults_page' => 'Seite',
		'pi_list_browseresults_prev' => '< Vorherige',
		'pi_list_browseresults_next' => 'Nдchste >',
		'pi_list_browseresults_displays' => 'Zeige Benutzer ###SPAN_BEGIN###%s bis %s</span> von insg. ###SPAN_BEGIN###%s an</span>',
		'pi_list_searchBox_search' => 'Suche',
	),
	'no' => Array (
		'listFieldHeader_username' => 'Brukernavn:',
		'listFieldHeader_name' => 'Navn:',
		'listFieldHeader_email' => 'E-post:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'By:',
		'listFieldHeader_zip' => 'Postnr:',
		'listFieldHeader_telephone' => 'Telefon:',
		'listFieldHeader_address' => 'Adresse:',
		'listFieldHeader_title' => 'Tittel:',
		'listFieldHeader_homepage' => 'Hjemmeside:',
		'listFieldHeader_company' => 'Firma:',
		'listFieldHeader_fax' => 'Faks:',
		'listFieldHeader_contribute' => 'Hva jeg шnsker е bidra med:',
		'listFieldHeader_personallife' => 'Mitt personlige liv:',
		'listFieldHeader_typo3experiences' => 'Erfaring:',
		'pi_list_browseresults_prev' => '< Forrige',
		'pi_list_browseresults_next' => 'Neste >',
		'pi_list_browseresults_displays' => 'Viser brukere ###SPAN_BEGIN###%s til %s</span> av ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Sшk',
	),
	'it' => Array (
		'listFieldHeader_username' => 'Username:',
		'listFieldHeader_name' => 'Nome:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Stato:',
		'listFieldHeader_city' => 'Cittа',
		'listFieldHeader_zip' => 'CAP',
		'listFieldHeader_telephone' => 'Telefono',
		'listFieldHeader_address' => 'Indirizzo',
		'listFieldHeader_title' => 'Titolo',
		'listFieldHeader_homepage' => 'Homepage',
		'listFieldHeader_company' => 'Azienda',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Desidero contribuire nel seguente modo:',
		'listFieldHeader_personallife' => 'La mia vita privata:',
		'listFieldHeader_typo3experiences' => 'Esperienza:',
		'pi_list_browseresults_page' => 'pagina',
		'pi_list_browseresults_prev' => '< indietro',
		'pi_list_browseresults_next' => 'avanti >',
		'pi_list_browseresults_displays' => 'Utenti da ###SPAN_BEGIN###%s a %s</span> su ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Cerca',
	),
	'fr' => Array (
	),
	'es' => Array (
		'listFieldHeader_username' => 'Nombre de usuario:',
		'listFieldHeader_name' => 'Nombre:',
		'listFieldHeader_email' => 'E-mail:',
		'listFieldHeader_country' => 'Paнs:',
		'listFieldHeader_city' => 'Ciudad:',
		'listFieldHeader_zip' => 'Cуdigo Postal:',
		'listFieldHeader_telephone' => 'Telйfono:',
		'listFieldHeader_address' => 'Direcciуn:',
		'listFieldHeader_title' => 'Cargo:',
		'listFieldHeader_homepage' => 'Direcciуn WEB:',
		'listFieldHeader_company' => 'Empresa:',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Con quй pretendo contribuir:',
		'listFieldHeader_personallife' => 'Mi vida personal:',
		'listFieldHeader_typo3experiences' => 'Experiencia:',
		'pi_list_browseresults_page' => 'Pбgina',
		'pi_list_browseresults_prev' => '< Anterior',
		'pi_list_browseresults_next' => 'Siguiente >',
		'pi_list_browseresults_displays' => 'Mostrando usuarios ###SPAN_BEGIN###del %s al %s</span> de un total de ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Buscar',
	),
	'nl' => Array (
		'listFieldHeader_username' => 'Gebruikersnaam:',
		'listFieldHeader_name' => 'Naam:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'Stad',
		'listFieldHeader_zip' => 'Postcode',
		'listFieldHeader_telephone' => 'Telefoon',
		'listFieldHeader_address' => 'Adres',
		'listFieldHeader_title' => 'Titel',
		'listFieldHeader_homepage' => 'Homepage:',
		'listFieldHeader_company' => 'Bedrijf',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Wat ik wil bijdragen:',
		'listFieldHeader_personallife' => 'Mijn persoonlijke leven:',
		'listFieldHeader_typo3experiences' => 'Ervaring:',
		'pi_list_browseresults_prev' => '< Vorige',
		'pi_list_browseresults_next' => 'Volgende >',
		'pi_list_browseresults_displays' => 'Weergegeven gebruikers ###SPAN_BEGIN###%s tot %s</span> van de ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Zoeken',
	),
	'cz' => Array (
	),
	'pl' => Array (
		'listFieldHeader_username' => 'Uїytkownik:',
		'listFieldHeader_name' => 'Nazwa:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Kraj:',
		'listFieldHeader_city' => 'Miasto',
		'listFieldHeader_zip' => 'Kod pocztowy',
		'listFieldHeader_telephone' => 'Telefon',
		'listFieldHeader_address' => 'Adres',
		'listFieldHeader_title' => 'Tytuі',
		'listFieldHeader_homepage' => 'Strona domowa',
		'listFieldHeader_company' => 'Firma',
		'listFieldHeader_fax' => 'Faks',
		'listFieldHeader_contribute' => 'Co chcк wnie¶ж/podzieliж siк:',
		'listFieldHeader_personallife' => 'Їycie prywatne:',
		'listFieldHeader_typo3experiences' => 'Do¶wiadczenie:',
		'pi_list_browseresults_page' => 'Strona',
		'pi_list_browseresults_prev' => '< Poprzednia',
		'pi_list_browseresults_next' => 'Nastкpna >',
		'pi_list_browseresults_displays' => 'Wy¶wietlanie uїytkownikуw ###SPAN_BEGIN###%s do %s</span> z ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Szukaj',
	),
	'si' => Array (
	),
	'fi' => Array (
		'listFieldHeader_username' => 'Kдyttдjдtunnus:',
		'listFieldHeader_name' => 'Nimi:',
		'listFieldHeader_email' => 'Sдhkцpostiosoite:',
		'listFieldHeader_country' => 'Maa:',
		'listFieldHeader_city' => 'Kaupunki:',
		'listFieldHeader_zip' => 'Postinumero:',
		'listFieldHeader_telephone' => 'Puhelin:',
		'listFieldHeader_address' => 'Osoite:',
		'listFieldHeader_title' => 'Arvo:',
		'listFieldHeader_homepage' => 'Kotisivu:',
		'listFieldHeader_company' => 'Yritys;',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Miten haluat osallsitua:',
		'listFieldHeader_personallife' => 'Henkilцkohtaista:',
		'listFieldHeader_typo3experiences' => 'Kokemus:',
		'pi_list_browseresults_page' => '.',
		'pi_list_browseresults_prev' => '< Edellinen',
		'pi_list_browseresults_next' => 'Seuraava >',
		'pi_list_browseresults_displays' => 'Nдytдn kдyttдjдt alkaen ###SPAN_BEGIN###%s aina %s</span> saakka kaikkiaan ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Haku',
	),
	'tr' => Array (
	),
	'se' => Array (
		'listFieldHeader_username' => 'Anvдndarnamn:',
		'listFieldHeader_name' => 'Namn:',
		'listFieldHeader_email' => 'Epost:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'Postadress',
		'listFieldHeader_zip' => 'Postnummer',
		'listFieldHeader_telephone' => 'Telefon',
		'listFieldHeader_address' => 'Adress',
		'listFieldHeader_title' => 'Titel',
		'listFieldHeader_homepage' => 'Hemsida',
		'listFieldHeader_company' => 'Fцretag',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Hur jag vill delta:',
		'listFieldHeader_personallife' => 'Mitt personliga liv:',
		'listFieldHeader_typo3experiences' => 'Erfarenhet:',
		'pi_list_browseresults_page' => 'Denna sida',
		'pi_list_browseresults_prev' => '< Tidigare',
		'pi_list_browseresults_next' => 'Nдsta >',
		'pi_list_browseresults_displays' => 'Visar anvдndare ###SPAN_BEGIN###%s till %s</span> av ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Sцk',
	),
	'pt' => Array (
		'listFieldHeader_username' => 'Utilizador:',
		'listFieldHeader_name' => 'Nome:',
		'listFieldHeader_email' => 'E-mail:',
		'listFieldHeader_country' => 'Paнs:',
		'listFieldHeader_city' => 'Cidade',
		'listFieldHeader_zip' => 'Cуdigo Postal',
		'listFieldHeader_telephone' => 'Telefone',
		'listFieldHeader_address' => 'Endereзo',
		'listFieldHeader_title' => 'Tнtulo',
		'listFieldHeader_homepage' => 'Homepage',
		'listFieldHeader_company' => 'Compania',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Em que eu quero contribuir:',
		'listFieldHeader_personallife' => 'Minha vida:',
		'listFieldHeader_typo3experiences' => 'Experiкncia:',
		'pi_list_browseresults_page' => '&nbsp;',
		'pi_list_browseresults_prev' => '< Anterior',
		'pi_list_browseresults_next' => 'Prуxima >',
		'pi_list_browseresults_displays' => 'Mostrando utilizadores de ###SPAN_BEGIN###%s a %s</span> de um total de ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Pesquisar',
	),
	'ru' => Array (
		'listFieldHeader_username' => 'Имя пользователя:',
		'listFieldHeader_name' => 'Ваше имя и фамилия:',
		'listFieldHeader_email' => 'Email (адрес электронной почты):',
		'listFieldHeader_country' => 'Страна:',
		'listFieldHeader_city' => 'Город',
		'listFieldHeader_zip' => 'Почтовый индекс',
		'listFieldHeader_telephone' => 'Телефон',
		'listFieldHeader_address' => 'Почтовый адрес',
		'listFieldHeader_title' => 'Титул, звание',
		'listFieldHeader_homepage' => 'Адрес веб-сайта',
		'listFieldHeader_company' => 'Название компании',
		'listFieldHeader_fax' => 'Телефакс',
		'listFieldHeader_contribute' => 'Пожелания:',
		'listFieldHeader_personallife' => 'Анкета:',
		'listFieldHeader_typo3experiences' => 'Опыт:',
		'pi_list_browseresults_page' => 'Страница',
		'pi_list_browseresults_prev' => '&laquo; предыдущие',
		'pi_list_browseresults_next' => 'следующие &raquo;',
		'pi_list_browseresults_displays' => 'Отображение пользователей ###SPAN_BEGIN###%s до %s</span> из ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Поиск',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
		'listFieldHeader_username' => 'Atuisup aqqa:',
		'listFieldHeader_name' => 'Ateq:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Nuna:',
		'listFieldHeader_city' => 'Illoqarfik:',
		'listFieldHeader_zip' => 'Postnormu:',
		'listFieldHeader_telephone' => 'Oqarasuaat:',
		'listFieldHeader_address' => 'Adresse:',
		'listFieldHeader_title' => 'Atorfik:',
		'listFieldHeader_homepage' => 'Nittartagaq:',
		'listFieldHeader_company' => 'Suliffik:',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Imatut tapeeqataarusuppunga:',
		'listFieldHeader_personallife' => 'Inuttut inuunera:',
		'listFieldHeader_typo3experiences' => 'Misilittakkakka:',
		'pi_list_browseresults_page' => '-',
		'pi_list_browseresults_prev' => '< Siulia',
		'pi_list_browseresults_next' => 'Tullia >',
		'pi_list_browseresults_displays' => 'Atuisut ###SPAN_BEGIN###%s</span> akornanni ###SPAN_BEGIN###%s-miit %s-mut</span> takutinneqarput',
		'pi_list_searchBox_search' => 'Ujaruk',
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
);
?>