<?php
/**
 * Language labels for module "web_txdanewslettersubscriptionM1"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'title' => 'NL Subscribers',
		'function1' => 'Newsletter categories',
		'function2' => 'Subscriber list',
		'ntitle' => 'Title',
		'descr' => 'Description',
		'subscr' => 'Subscribers',
		'listEmail' => 'List of unique email addresses',
		'goBack' => 'Go back',
		'list' => 'list',
		'loadpreset' => 'Load preset',
		'savepreset' => 'Save current query as',
		'deletepreset' => 'Delete preset',
		'number_subscr' => 'Number of subscribers',
		'action' => 'Select action',
		'and_subscr' => 'AND subscribed to this list',
		'or_subscr' => 'OR subscribed to this list',
		'not_subscr' => 'NOT subscribed to this list',
		'lists' => 'Lists',
		'field' => 'Field',
		'NOT' => 'NOT',
		'Show' => 'Show',
		'Mode' => 'Method',
		'comparison' => 'Comparison',
		'value' => 'Value',
		'userAttrib' => 'User attributes',
		'localAttrib' => 'Local attributes',
		'warning_more_el' => 'WARNING: More than one content element with this plugin on the page. Using the first occurence as template for local attributes.',
		'output_simple' => 'Simple email list',
		'output_oodoc' => 'OpenOffice Calc Spreadsheet',
		'output_csv' => 'CSV of selected',
		'output_make' => 'Make query',
		'output_unique' => 'Guarantee unique email addresses',
		'header_output' => 'Output type',
		'header_preset' => 'Presets',
		'sel_UsersSel' => 'Users selected',
		'sel_NonUsersSel' => 'Non-users selected',
		'sel_clause' => 'selected by this clause',
		'sel_labelResults' => 'results',
		'sel_labelAny' => 'Select subscribers to all newsletters',
		'sel_labelSel' => 'Select subscribers to',
		'sel_labelAND' => 'and',
		'sel_labelOR' => 'or',
		'sel_labelExcept' => '<em>except</em> subscribers to',
		'sel_checked' => 'Checked',
		'sel_equal' => 'equal to',
		'sel_first' => 'first part equals',
		'sel_last' => 'last part equals',
		'sel_contains' => 'contains',
		'sel_less' => 'less than',
		'sel_greater' => 'greater than',
		'sel_between' => 'between',
		'sel_true' => 'is set',
		'download_as_file' => 'Download result as a file',
		'needHelp' => 'Need help? Click here (english)',
	),
	'dk' => Array (
		'title' => 'Nyhedsbrevstilmeldte',
		'function1' => 'Kategorier af nyhedsbreve',
		'function2' => 'Tilmeldingsliste',
		'ntitle' => 'Titel',
		'descr' => 'Beskrivelse',
		'subscr' => 'Tilmeldte',
		'listEmail' => 'Liste af unikke email adresser',
		'goBack' => 'Gå tilbage',
		'list' => 'liste',
		'loadpreset' => 'Hent forudindstillinger',
		'savepreset' => 'Gem nuværende instillinger som',
		'deletepreset' => 'Slet forudindstillinger',
		'number_subscr' => 'Antal tilmeldte',
		'action' => 'Vælg handling',
		'and_subscr' => 'OG tilmeldt til denne liste',
		'or_subscr' => 'ELLER tilmeldt til denne liste',
		'not_subscr' => 'IKKE tilmeldt til denne liste',
		'lists' => 'Lister',
		'field' => 'Felt',
		'NOT' => 'IKKE',
		'Show' => 'Vis',
		'Mode' => 'Metode',
		'comparison' => 'Sammenligning',
		'value' => 'Værdi',
		'userAttrib' => 'Bruger egenskaber',
		'localAttrib' => 'Lokale egenskaber',
		'warning_more_el' => 'ADVARSEL: Der er mere end et indholdselement med denne plugin på siden. Den først fundne benyttes som skabelon for lokale egenskaber.',
		'output_email' => 'Optælling',
		'output_simple' => 'Simpel email liste',
		'output_oodoc' => 'OpenOffice Calc Regneark',
		'output_csv' => 'CSV af valgte',
		'output_make' => 'Udfør udvælgelse',
		'output_unique' => 'Sikre unikke emailadresser',
		'header_output' => 'Resultattype',
		'header_preset' => 'Forudindstillinger',
		'sel_UsersSel' => 'Brugere udvalgt',
		'sel_NonUsersSel' => 'Ikke-brugere udvalgt',
		'sel_clause' => 'udvalgt med denne betingelse',
		'sel_labelResults' => 'resultater',
		'sel_labelAny' => 'Vælg tilmeldte til alle nyhedsbreve',
		'sel_labelSel' => 'Vælg tilmeldte til',
		'sel_labelAND' => 'og',
		'sel_labelOR' => 'eller',
		'sel_labelExcept' => '<em>pånær</em> tilmeldte til',
		'sel_checked' => 'Afkrydset',
		'sel_equal' => 'lig med',
		'sel_first' => 'første del lig med',
		'sel_last' => 'sidste del lig med',
		'sel_contains' => 'indeholder',
		'sel_less' => 'mindre end',
		'sel_greater' => 'større end',
		'sel_between' => 'mellem',
		'sel_true' => 'er sat',
		'download_as_file' => 'Hent resultatet som fil',
		'needHelp' => 'Brug for hjælp? Klik her (engelsk)',
	),
	'de' => Array (
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
);
?>