<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'jw_calendar.pi_flexform.sheet_general' => 'General Settings',
		'jw_calendar.pi_flexform.view_mode' => 'View mode',
		'jw_calendar.pi_flexform.view_month' => 'Monthview',
		'jw_calendar.pi_flexform.view_list' => 'Listview',
		'jw_calendar.pi_flexform.view_week' => 'Weekview',
		'jw_calendar.pi_flexform.view_day' => 'Dayview',
		'jw_calendar.pi_flexform.view_single' => 'Singleview',
		'jw_calendar.pi_flexform.view_feEntry' => 'feEntryform',
		'jw_calendar.pi_flexform.view_spec' => 'SpecialViews',
		'jw_calendar.pi_flexform.help' => 'Help',
		'jw_calendar.pi_flexform.changeViewMode' =>'Change view between',
		'jw_calendar.pi_flexform.dateFormat' => 'Date format def: %a, %b %d, %Y',
		'jw_calendar.pi_flexform.timeFormat' => 'Time format def: %I:%M %p',
		'jw_calendar.pi_flexform.entryCount' => 'Events in Listview def: 8',
		'jw_calendar.pi_flexform.startTime' => 'Start Time in Listview',
		'jw_calendar.pi_flexform.entryPeriod' => 'Entry Period ex.:+3 weeks',
		'jw_calendar.pi_flexform.image_maxWidth' => 'Image maxWidth in Singleview def:100',
		'jw_calendar.pi_flexform.dayFormat' => 'day Format in MONTH View (def:"%d")',
		'jw_calendar.pi_flexform.showWeeksAsRows' => 'Show weeks as row (def:column)',
		'jw_calendar.pi_flexform.onlyDaysofMonth' => 'Don\'t show days outside of Month',
		'jw_calendar.pi_flexform.showWeeksDisabled' => 'Don\'t show Weeks in MONTH View',
		'jw_calendar.pi_flexform.miniMonthView' => 'MONTH View without Events (for small view)',
		'jw_calendar.pi_flexform.wrapItem' => 'Don\'n Wrap items in Month View (def: 0)',
		'jw_calendar.pi_flexform.wrapItemCatLen' => 'Letters of category in wraped items (def: 0)',
		'jw_calendar.pi_flexform.headerCategories_show' => 'Show Categories in Title',
		'jw_calendar.pi_flexform.headerCategories_glue' => 'Between Categorie in Title def: "-" ',
		'jw_calendar.pi_flexform.headerCategories_link' => 'Link Categories in Title',
		'jw_calendar.pi_flexform.select_deselect_categories' => 'Select category behaviour',
        'jw_calendar.pi_flexform.category_selection_showAll' => 'Show all categories by default',
        'jw_calendar.pi_flexform.category_selection_showSelected' => 'Show only selected categories',
        'jw_calendar.pi_flexform.category_selection_DontShowSelected' => 'Show all but selected categories',
        'jw_calendar.pi_flexform.category_selection_notCategorized' => '[no category]',
		'jw_calendar.pi_flexform.category_selection' => 'Select category',
		'jw_calendar.pi_flexform.template_file' => 'Template file',

		'jw_calendar.pi_flexform.sheet_Month_View' => 'Month View',
		'jw_calendar.pi_flexform.showEventBegin' => 'Show Event Time',
		'jw_calendar.pi_flexform.maxDaynameLenght' => 'Max Dayname Lenght',
			

		'jw_calendar.pi_flexform.sheet_List_View' => 'List View',

		'jw_calendar.pi_flexform.sheet_Week_View' => 'Week View',
		'jw_calendar.pi_flexform.startHour' => 'Start Hour',
		'jw_calendar.pi_flexform.stopHour' => 'End Hour',
		'jw_calendar.pi_flexform.queryEmptyWeeks' => 'query Search Weeks Max',
		'jw_calendar.pi_flexform.max_hours' => 'Last Hour left/right',

		'jw_calendar.pi_flexform.sheet_Day_View' => 'Day View',
		'jw_calendar.pi_flexform.dayDateFormat' => 'Date format in Title',
		'jw_calendar.pi_flexform.DayviewPluginUid' => 'Day View Plugin Uid',
		'jw_calendar.pi_flexform.DayviewPage' => 'Day View Page',
		'jw_calendar.pi_flexform.simpleDayView' => 'set this if Dayview not combined with Monthview (def.:false)',
		'jw_calendar.pi_flexform.daySingleView' => 'Events like Singleview (def.:false)',
		'jw_calendar.pi_flexform.mixedModeDisplay' => 'First num Events like Singleview',
		'jw_calendar.pi_flexform.linkPrevNextDay' => 'link Prev/Next Day (def.:false)',
		'jw_calendar.pi_flexform.queryfirstDayFound' => 'query first Day found (def.:true)',
		'jw_calendar.pi_flexform.querySearchDayMax' => 'query Search Day Max (def.:30)',

		'jw_calendar.pi_flexform.sheet_Single_View' => 'Single View',
		'jw_calendar.pi_flexform.singlePluginUid' => 'singleView Plugin Uid',
		'jw_calendar.pi_flexform.singlePage' => 'singleView page',
		'jw_calendar.pi_flexform.organizerTable' => 'Organizer Table',
		'jw_calendar.pi_flexform.table_organizer' => 'Calendar Organizer Table',
		'jw_calendar.pi_flexform.table_fe_users' => 'FE_Users Table as Organizer',

		'jw_calendar.pi_flexform.sheet_FE_Entries' => 'FE_Entries',
		'jw_calendar.pi_flexform.FE_Entry' => 'FE Entries alowed',
		'jw_calendar.pi_flexform.FE_Pencil' => 'show as Pencil each day',
		'jw_calendar.pi_flexform.FE_Button' => 'show Button for FE Entry',
		'jw_calendar.pi_flexform.FE_Page' => 'FE_Entry page',
		'jw_calendar.pi_flexform.FE_storagePid' => 'FE_Entries store in Page',
		'jw_calendar.pi_flexform.FE_showControlled' => 'FE Entries first hidden',
		'jw_calendar.pi_flexform.FE_minuteStep' => 'Step in minutes',
		'jw_calendar.pi_flexform.FE_backwardYears' => 'backwardYears def:0',
		'jw_calendar.pi_flexform.FE_forwardYears' => 'forwardYears def:2',
		'jw_calendar.pi_flexform.FE_Image_alowed' => 'FE Entries with Image alowed (def.: false)',
		'jw_calendar.pi_flexform.FE_Image_noOverwrite' => 'Imageupload Overwrite alowed (def.: false)',
		'jw_calendar.pi_flexform.FE_editFE_Entries' => 'Edit previous FE Entries alowed (def.: false)',
		'jw_calendar.pi_flexform.FE_Image_maxSize' => 'Image Upload max Size def:50000',
		'jw_calendar.pi_flexform.FE_Mail_enabled' => 'Enable Mail Notification if FE Entry appears',
		'jw_calendar.pi_flexform.FE_Mail_recipient' => 'Mail recipient',
		'jw_calendar.pi_flexform.FE_Mail_subject' => 'Mail subject',
		'jw_calendar.pi_flexform.FE_Mail_from' => 'Mail from',
		
		'jw_calendar.pi_flexform.sheet_Tooltip' => 'Tooltips',
		'jw_calendar.pi_flexform.toolTipShow' => 'Show Tooltips in Monthview',
		'jw_calendar.pi_flexform.timeFormatBegin' => 'Time format begin def: From %H:%M',
		'jw_calendar.pi_flexform.timeFormatEnd' => 'time format end def: to %H:%M',
		'jw_calendar.pi_flexform.timeFormatBeginMdays' => 'Time format Events > 24h def: From %d.%b: %H:%M',
		'jw_calendar.pi_flexform.timeFormatEndMdays' => 'time format for Events > 24h def:to %d.%b: %H:%M',
		'jw_calendar.pi_flexform.toolTipTitle' => 'Show Title in tooltip',
		'jw_calendar.pi_flexform.toolTipTeaser' => 'Show teaser in tooltip',
		'jw_calendar.pi_flexform.toolTipDescription' => 'Show Description in tooltip',
		'jw_calendar.pi_flexform.toolTipWordwrap' => 'Wordwrap in tooltip (IExplorer) def:60',

	),
	'de' => Array (
		'jw_calendar.pi_flexform.sheet_general' => 'Allgemeine Einstellungen',
		'jw_calendar.pi_flexform.view_mode' => 'Kalender Ansicht',
		'jw_calendar.pi_flexform.view_month' => 'Monatsansicht',
		'jw_calendar.pi_flexform.view_list' => 'Listenansicht',
		'jw_calendar.pi_flexform.view_week' => 'Wochenansicht',
		'jw_calendar.pi_flexform.view_day' => 'Tagesansicht',
		'jw_calendar.pi_flexform.view_single' => 'Einzelansicht (Eintrag)',
		'jw_calendar.pi_flexform.view_feEntry' => 'FE Ereigniseintrag',
		'jw_calendar.pi_flexform.view_spec' => 'Spezialansichten',
		'jw_calendar.pi_flexform.help' => 'Hilfe',
		'jw_calendar.pi_flexform.changeViewMode' =>'Ansicht wechseln zwischen',
		'jw_calendar.pi_flexform.dateFormat' => 'Datumsformat def: %a, %b %d, %Y',
		'jw_calendar.pi_flexform.timeFormat' => 'Zeitformatt def: %I:%M %p',
		'jw_calendar.pi_flexform.entryCount' => 'Anzahl Ereignisse in Listenansicht def: 8',
		'jw_calendar.pi_flexform.startTime' => 'Startzeit in Listview',
		'jw_calendar.pi_flexform.entryPeriod' => 'Ereignis Zeitraum Bsp.:+3 weeks',
		'jw_calendar.pi_flexform.singlePage' => 'singleView Seite',
		'jw_calendar.pi_flexform.image_maxWidth' => 'max. Bildbreite in Singleview def:100',
		'jw_calendar.pi_flexform.dayFormat' => 'Tag Format in Monatsansicht (def:"%d")',
		'jw_calendar.pi_flexform.showWeeksAsRows' => 'Zeige Woche in der Reihe (def:Spalte)',
		'jw_calendar.pi_flexform.onlyDaysofMonth' => 'Tage außerhalb des akt. Monats nicht anzeigen',
		'jw_calendar.pi_flexform.showWeeksDisabled' => 'Woche des Jahres nicht anzeigen',
		'jw_calendar.pi_flexform.miniMonthView' => 'Monatsansicht ohne Ereignisanzeige(für kleine Ansichten)',
		'jw_calendar.pi_flexform.wrapItem' => 'Ereignisse in einfacher Art anzeigen(def: 0)',
		'jw_calendar.pi_flexform.wrapItemCatLen' => 'Anzahl Zeichen der Kategorie (def: 0)',
		'jw_calendar.pi_flexform.headerCategories_show' => 'Kategorien im Kopf des Kalenders anzeigen',
		'jw_calendar.pi_flexform.headerCategories_glue' => 'Zeichen zwischen den Kategorien def: "-" ',
		'jw_calendar.pi_flexform.headerCategories_link' => 'Kategorienfilter im Kopf des Kalenders',
		'jw_calendar.pi_flexform.select_deselect_categories' => 'Auswahl des Verhaltens der Kategorienauswahl',
        'jw_calendar.pi_flexform.category_selection_showAll' => 'Zeige alle Kategorien',
        'jw_calendar.pi_flexform.category_selection_showSelected' => 'Zeige ausgewähle Kategorien',
        'jw_calendar.pi_flexform.category_selection_DontShowSelected' => 'Zeige alle, außer den ausgewählten Kategorien',
        'jw_calendar.pi_flexform.category_selection_notCategorized' => '[keine Kategorie]',
		'jw_calendar.pi_flexform.category_selection' => 'Kategorienauswahl',
		'jw_calendar.pi_flexform.template_file' => 'Template Datei',

		'jw_calendar.pi_flexform.sheet_Month_View' => 'Monatsansicht',
		'jw_calendar.pi_flexform.showEventBegin' => 'Zeige Ereigniszeit',
		'jw_calendar.pi_flexform.maxDaynameLenght' => 'Max Länge der Tagesabkürzung',

		'jw_calendar.pi_flexform.sheet_List_View' => 'Listenansicht',

		'jw_calendar.pi_flexform.sheet_Week_View' => 'Wochenansicht',
		'jw_calendar.pi_flexform.startHour' => 'Start Stunde',
		'jw_calendar.pi_flexform.stopHour' => 'Ende Stunde',
		'jw_calendar.pi_flexform.queryEmptyWeeks' => 'Max Anzahl Wochen vor/nach durchsuchen',
		'jw_calendar.pi_flexform.max_hours' => 'Letzte Stunde links',
			

		'jw_calendar.pi_flexform.sheet_Day_View' => 'Tagesansicht',
		'jw_calendar.pi_flexform.dayDateFormat' => 'Datums format im Titel',
		'jw_calendar.pi_flexform.DayviewPluginUid' => 'Tagesansicht Plugin Uid',
		'jw_calendar.pi_flexform.DayviewPage' => 'Tagesansicht Seite',
		'jw_calendar.pi_flexform.simpleDayView' => 'setzen wenn Tageansicht in Kombination mit MONTH',
		'jw_calendar.pi_flexform.daySingleView' => 'Ereignisse groß anzeigen (wie Einzelansicht)',
		'jw_calendar.pi_flexform.mixedModeDisplay' => 'Zeige num Ereignisse groß',
		'jw_calendar.pi_flexform.linkPrevNextDay' => 'link Tag Vorher / Nachher',
		'jw_calendar.pi_flexform.queryfirstDayFound' => 'Finde ersten Tag mit Ereignissen',
		'jw_calendar.pi_flexform.querySearchDayMax' => 'Max Anzahl Tage vor/nach durchsuchen (def.:30)',

		'jw_calendar.pi_flexform.sheet_Single_View' => 'Einzelansicht',
		'jw_calendar.pi_flexform.singlePluginUid' => 'Einzelansicht Plugin Uid',
		'jw_calendar.pi_flexform.singlePage' => 'Einzelansicht Seite',
		'jw_calendar.pi_flexform.organizerTable' => 'Organizer Table',
		'jw_calendar.pi_flexform.table_organizer' => 'Calendar Organizer Table',
		'jw_calendar.pi_flexform.table_fe_users' => 'FE_Users Table as Organizer',

		'jw_calendar.pi_flexform.sheet_FE_Entries' => 'FE Einträge',
		'jw_calendar.pi_flexform.FE_Entry' => 'FE Einträge erlaubt',
		'jw_calendar.pi_flexform.FE_Pencil' => 'Zeige link zum FE Eintrag als Bleistiftsymbol',
		'jw_calendar.pi_flexform.FE_Button' => 'Zeige link  zum FE Eintrag als Button',
		'jw_calendar.pi_flexform.FE_Page' => 'FE Eintragsseite (def.:akt.Seite)',
		'jw_calendar.pi_flexform.FE_storagePid' => 'FE Einträge unter dieser Seite speichern (def.:akt.Seite)',
		'jw_calendar.pi_flexform.FE_showControlled' => 'FE Einträge werden erst als verborgen markiert',
		'jw_calendar.pi_flexform.FE_minuteStep' => 'Schrittweite in Minuten',
		'jw_calendar.pi_flexform.FE_backwardYears' => 'Zurückliegende Jahre (def.:0)',
		'jw_calendar.pi_flexform.FE_forwardYears' => 'Zukünftige Jahre (def.:2)',
		'jw_calendar.pi_flexform.FE_Image_alowed' => 'FE Einräge mit Bild erlauben',
		'jw_calendar.pi_flexform.FE_Image_noOverwrite' => 'Bild upload mit überschreiben erlauben',
		'jw_calendar.pi_flexform.FE_editFE_Entries' => 'Erlaube dem FE Beutzer das editieren alter Einträge',
		'jw_calendar.pi_flexform.FE_Image_maxSize' => 'Max. Größe des Bildes zum hochladen def:50000',
		'jw_calendar.pi_flexform.FE_Mail_enabled' => 'Mail Benachrichtigung bei neuem FE Eintrag',
		'jw_calendar.pi_flexform.FE_Mail_recipient' => 'Mail Empfänger',
		'jw_calendar.pi_flexform.FE_Mail_subject' => 'Mail subject',
		'jw_calendar.pi_flexform.FE_Mail_from' => 'Mail von',
		
		'jw_calendar.pi_flexform.sheet_Tooltip' => 'Tooltips',
		'jw_calendar.pi_flexform.toolTipShow' => 'Zeige Tooltips in der Monatsansicht',
		'jw_calendar.pi_flexform.timeFormatBegin' => 'Zeitformat Anfang def: From %H:%M',
		'jw_calendar.pi_flexform.timeFormatEnd' => 'Zeitformat Ende def: to %H:%M',
		'jw_calendar.pi_flexform.timeFormatBeginMdays' => 'Zeitformat Anfang Events > 24h def: From %d.%b: %H:%M',
		'jw_calendar.pi_flexform.timeFormatEndMdays' => 'Zeitformat Ende Events > 24h def:to %d.%b: %H:%M',
		'jw_calendar.pi_flexform.toolTipTitle' => 'Zeige Titel in tooltip',
		'jw_calendar.pi_flexform.toolTipTeaser' => 'Zeige teaser in tooltip',
		'jw_calendar.pi_flexform.toolTipDescription' => 'Zeige Beschreibung in tooltip',
		'jw_calendar.pi_flexform.toolTipWordwrap' => 'Wordumbruch in tooltip (IExplorer) def:60',

	),
);
?>
