<?php
/**
 * Language labels for database tables/fields belonging to extension "sr_static_info"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'static_countries_item.cn_iso_2' => 'ISO 3166-1 A2 Country code:',
		'static_countries_item.cn_iso_3' => 'ISO 3166-1 A3 Country code:',
		'static_countries_item.cn_iso_nr' => 'ISO 3166-1 Nr Country code:',
		'static_countries_item.cn_currency_iso_nr' => 'ISO 4217 Nr Currency code:',
		'static_countries_item.cn_currency_iso_3' => 'ISO 4217 A3 Currency code:',
		'static_countries_item.cn_address_format_9' => 'city - region-code/zip',
		'static_country_zones_item.zn_country_iso_nr' => 'ISO 3166-1 Nr Country code:',
		'static_country_zones_item.zn_country_iso_2' => 'ISO 3166-1 A2 Country code:',
		'static_country_zones_item.zn_country_iso_3' => 'ISO 3166-1 A3 Country code:',
		'static_country_zones_item.zn_code' => 'ISO 3166-2 Country Zone code:',
		'static_country_zones_item.zn_name_local' => 'Local name:',
		'static_languages_item.lg_iso_2' => 'ISO 639-1 A2 Language code:',
		'static_languages_item.lg_collate_locale' => 'Collating locale:',
		'static_currencies_item.cu_iso_3' => 'ISO 4217 A3 Currency code:',
		'static_currencies_item.cu_iso_nr' => 'ISO 4217 Nr Currency code:',
		'static_taxes.title' => 'Static taxes',
		'static_taxes_item.cn_iso_2' => 'ISO 3166-1 A2 Country code:',
		'static_taxes_item.cn_iso_3' => 'ISO 3166-1 A3 Country code:',
		'static_taxes_item.cn_iso_nr' => 'ISO 3166-1 Nr Country code:',
		'static_taxes_item.zn_code' => 'ISO 3166-2 Country Zone code:',
		'static_taxes_item.tx_name_en' => 'Tax name (EN):',
		'static_taxes_item.tx_code' => 'Tax code:',
		'static_taxes_item.tx_scope' => 'Juridiction:',
		'static_taxes_item.tx_scope.I.0' => 'Country',
		'static_taxes_item.tx_scope.I.1' => 'State/province',
		'static_taxes_item.tx_class' => 'Class:',
		'static_taxes_item.tx_class.I.0' => 'Taxable goods',
		'static_taxes_item.tx_class.I.1' => 'Taxable services',
		'static_taxes_item.tx_class.I.2' => 'Taxable goods and services',
		'static_taxes_item.tx_rate' => 'Rate:',
		'static_taxes_item.tx_priority' => 'Priority:',
	),
	'dk' => Array (
	),
	'de' => Array (
		'static_countries_item.cn_iso_2' => 'Ländercode nach ISO 3166 A2:',
		'static_countries_item.cn_iso_3' => 'Ländercode nach ISO 3166 A3:',
		'static_countries_item.cn_iso_nr' => 'Ländercode nach ISO 3166 Nr:',
		'static_countries_item.cn_currency_iso_nr' => 'Währungscode nach ISO 4217 Nr:',
		'static_countries_item.cn_currency_iso_3' => 'Währungscode nach ISO 4217 A3:',
		'static_country_zones_item.zn_country_iso_nr' => 'Ländercode nach ISO 3166 Nr:',
		'static_country_zones_item.zn_country_iso_2' => 'Ländercode nach ISO 3166 A2:',
		'static_country_zones_item.zn_country_iso_3' => 'Ländercode nach ISO 3166 A3:',
		'static_country_zones_item.zn_code' => 'Landesgliederungscode nach ISO 3166-2:',
		'static_country_zones_item.zn_name_local' => 'Lokaler Name:',
		'static_languages_item.lg_iso_2' => 'Sprachcode nach ISO 639-1 A2:',
		'static_currencies_item.cu_iso_3' => 'Währungscode nach ISO 4217 A3:',
		'static_currencies_item.cu_iso_nr' => 'Währungscode nach ISO 4217 Nr:',
		'static_taxes.title' => 'Steuern',
		'static_taxes_item.cn_iso_2' => 'Ländercode nach ISO 3166 A2:',
		'static_taxes_item.cn_iso_3' => 'Ländercode nach ISO 3166 A3:',
		'static_taxes_item.cn_iso_nr' => 'Ländercode nach ISO 3166 Nr:',
		'static_taxes_item.zn_code' => 'Zonenkürzel:',
		'static_taxes_item.tx_name_en' => 'Steuername (EN):',
		'static_taxes_item.tx_code' => 'Steuerkürzel:',
		'static_taxes_item.tx_scope' => 'Geltungsbereich:',
		'static_taxes_item.tx_scope.I.0' => 'Land',
		'static_taxes_item.tx_scope.I.1' => 'Bundesland/Provinz',
		'static_taxes_item.tx_class' => 'Steuerklasse:',
		'static_taxes_item.tx_class.I.0' => 'Steuerpflichtge Waren',
		'static_taxes_item.tx_class.I.1' => 'Steuerpflichtge Dienstleistungen',
		'static_taxes_item.tx_class.I.2' => 'Steuerpflichtge Waren und Dienstleistungen',
		'static_taxes_item.tx_rate' => 'Steuersatz:',
		'static_taxes_item.tx_priority' => 'Priorität:',
	),
	'no' => Array (
	),
	'it' => Array (
		'static_countries_item.cn_iso_2' => 'Codice nazione ISO 3166-1 A2:',
		'static_countries_item.cn_iso_3' => 'Codice nazione ISO 3166-1 A3:',
		'static_countries_item.cn_iso_nr' => 'Numero codice nazione ISO 3166-1 Nr:',
		'static_countries_item.cn_currency_iso_nr' => 'Numero codice valuta ISO 4217 Nr:',
		'static_countries_item.cn_currency_iso_3' => 'Codice valuta ISO 4217 A3:',
		'static_country_zones_item.zn_country_iso_nr' => 'Numero codice nazione ISO:',
		'static_country_zones_item.zn_country_iso_2' => 'Codice nazione ISO 2:',
		'static_country_zones_item.zn_country_iso_3' => 'Codice nazione ISO 3:',
		'static_country_zones_item.zn_code' => 'Codice zona:',
		'static_languages_item.lg_iso_2' => 'Codice lingua ISO 2:',
		'static_currencies_item.cu_iso_3' => 'Codice valuta ISO 3:',
		'static_currencies_item.cu_iso_nr' => 'Numero codice valuta ISO:',
	),
	'fr' => Array (
		'static_countries_item.cn_iso_2' => 'Code de pays ISO 3166-1 A2:',
		'static_countries_item.cn_iso_3' => 'Code de pays ISO 3166-1 A3:',
		'static_countries_item.cn_iso_nr' => 'Code de pays ISO 3166-1 numérique:',
		'static_countries_item.cn_currency_iso_nr' => 'Code de devise ISO 4217 numérique:',
		'static_countries_item.cn_currency_iso_3' => 'Code de devise ISO 4217 A3:',
		'static_countries_item.cn_address_format_9' => 'localité - code-de-région/code-postal',
		'static_country_zones_item.zn_country_iso_nr' => 'Code de pays ISO 3166-1 numérique:',
		'static_country_zones_item.zn_country_iso_2' => 'Code de pays ISO 3166-1 A2:',
		'static_country_zones_item.zn_country_iso_3' => 'Code de pays ISO 3166-1 A3:',
		'static_country_zones_item.zn_code' => 'Code de subdivision de pays ISO 3166-2:',
		'static_country_zones_item.zn_name_local' => 'Nom local de subdivision de pays:',
		'static_languages_item.lg_iso_2' => 'Code de langue ISO 639-1 A2:',
		'static_languages_item.lg_collate_locale' => 'Localisation pour la comparaison de chaînes:',
		'static_currencies_item.cu_iso_3' => 'Code de devise ISO 4217 A3:',
		'static_currencies_item.cu_iso_nr' => 'Code de devise ISO 4217 numérique:',
		'static_taxes.title' => 'Taxe - Données statiques',
		'static_taxes_item.cn_iso_2' => 'Code de pays ISO 3166-1 A2:',
		'static_taxes_item.cn_iso_3' => 'Code de pays ISO 3166-1 A3:',
		'static_taxes_item.cn_iso_nr' => 'Code de pays ISO 3166-1 numérique:',
		'static_taxes_item.zn_code' => 'Code de subdivision de pays ISO 3166-2:',
		'static_taxes_item.tx_name_en' => 'Dénomination de la taxe:',
		'static_taxes_item.tx_code' => 'Code de taxe:',
		'static_taxes_item.tx_scope' => 'Juridiction:',
		'static_taxes_item.tx_scope.I.0' => 'Pays',
		'static_taxes_item.tx_scope.I.1' => 'État/province',
		'static_taxes_item.tx_class' => 'Classe:',
		'static_taxes_item.tx_class.I.0' => 'Biens taxables',
		'static_taxes_item.tx_class.I.1' => 'Services taxables',
		'static_taxes_item.tx_class.I.2' => 'Biens et services taxables',
		'static_taxes_item.tx_rate' => 'Taux:',
		'static_taxes_item.tx_priority' => 'Priorité:',
	),
	'es' => Array (
		'static_countries_item.cn_iso_2' => 'Código de país ISO 3166-1 A2:',
		'static_countries_item.cn_iso_3' => 'Código de país ISO 3166-1 A3:',
		'static_countries_item.cn_iso_nr' => 'Código de país ISO 3166-1 numérico:',
		'static_countries_item.cn_currency_iso_nr' => 'Código de divisa ISO 4217 numérico:',
		'static_countries_item.cn_currency_iso_3' => 'Código de divisa ISO 4217 A3:',
		'static_country_zones_item.zn_country_iso_nr' => 'Código de país ISO numérico:',
		'static_country_zones_item.zn_country_iso_2' => 'Código de país ISO 2:',
		'static_country_zones_item.zn_country_iso_3' => 'Código de país ISO 3:',
		'static_country_zones_item.zn_code' => 'Código de subdivisión de país:',
		'static_country_zones_item.zn_name_local' => 'Nombre de subdivisión de país:',
		'static_languages_item.lg_iso_2' => 'Código de idioma ISO 2:',
		'static_languages_item.lg_collate_locale' => 'Localidad para la comparación de cadenas:',
		'static_currencies_item.cu_iso_3' => 'Código de divisa ISO 3:',
		'static_currencies_item.cu_iso_nr' => 'Código de divisa ISO numérico:',
		'static_taxes.title' => 'Impuesto - Datos státicos',
		'static_taxes_item.cn_iso_2' => 'Código de país ISO 2:',
		'static_taxes_item.cn_iso_3' => 'Código de país ISO 3:',
		'static_taxes_item.cn_iso_nr' => 'Código de país ISO numérico:',
		'static_taxes_item.zn_code' => 'Código de subdivisión de país:',
		'static_taxes_item.tx_name_en' => 'Denominación del impuesto (EN):',
		'static_taxes_item.tx_code' => 'Código de impuesto:',
		'static_taxes_item.tx_scope' => 'Juridicción:',
		'static_taxes_item.tx_scope.I.0' => 'País',
		'static_taxes_item.tx_scope.I.1' => 'Estado/provincia',
		'static_taxes_item.tx_class' => 'Clase:',
		'static_taxes_item.tx_class.I.0' => 'Bienes imponibles',
		'static_taxes_item.tx_class.I.1' => 'Servicios imponibles',
		'static_taxes_item.tx_class.I.2' => 'Bienes y servicios imponibles',
		'static_taxes_item.tx_rate' => 'Tasa del impuesto:',
		'static_taxes_item.tx_priority' => 'Prioridad:',
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
		'static_countries_item.cn_iso_2' => 'Kod kraju ISO 3166-1 A2:',
		'static_countries_item.cn_iso_3' => 'Kod kraju ISO 3166-1 A3:',
		'static_countries_item.cn_iso_nr' => 'Kod kraju ISO 3166-1 Nr:',
		'static_countries_item.cn_currency_iso_nr' => 'Kod waluty ISO 4217 nr:',
		'static_countries_item.cn_currency_iso_3' => 'Kod waluty ISO 4217 A3:',
		'static_country_zones_item.zn_country_iso_nr' => 'Kod kraju ISO nr:',
		'static_country_zones_item.zn_country_iso_2' => 'Kod kraju ISO 2:',
		'static_country_zones_item.zn_country_iso_3' => 'Kod kraju ISO 3:',
		'static_country_zones_item.zn_code' => 'Kod strefy:',
		'static_languages_item.lg_iso_2' => 'Kod jêzyka ISO 2:',
		'static_currencies_item.cu_iso_3' => 'Kod waluty ISO 3:',
		'static_currencies_item.cu_iso_nr' => 'Kod waluty ISO nr:',
	),
	'si' => Array (
	),
	'fi' => Array (
		'static_countries_item.cn_iso_2' => 'ISO 2 maakoodi:',
		'static_countries_item.cn_iso_3' => 'ISO 3 maakoodi:',
		'static_countries_item.cn_iso_nr' => 'ISO nr maakoodi:',
		'static_countries_item.cn_currency_iso_nr' => 'ISO nr valuuttakoodi:',
		'static_countries_item.cn_currency_iso_3' => 'ISO 3 valuuttakoodi:',
		'static_country_zones_item.zn_country_iso_nr' => 'ISO nr maakoodi:',
		'static_country_zones_item.zn_country_iso_2' => 'ISO 2 maakoodi:',
		'static_country_zones_item.zn_country_iso_3' => 'ISO 3 maakoodi:',
		'static_country_zones_item.zn_code' => 'Vyöhykekoodi:',
		'static_country_zones_item.zn_name_local' => 'Paikallinen nimi',
		'static_languages_item.lg_iso_2' => 'ISO 2 maakoodi:',
		'static_languages_item.lg_collate_locale' => 'Paikallinen järjestys (locale):',
		'static_currencies_item.cu_iso_3' => 'ISO 3 valuuttakoodi:',
		'static_currencies_item.cu_iso_nr' => 'ISO nr valuuttakoodi:',
		'static_taxes.title' => 'Pysyvät verot',
		'static_taxes_item.cn_iso_2' => 'ISO 2 maakoodi:',
		'static_taxes_item.cn_iso_3' => 'ISO 3 maakoodi:',
		'static_taxes_item.cn_iso_nr' => 'ISO nr maakoodi:',
		'static_taxes_item.zn_code' => 'Aluekoodi:',
		'static_taxes_item.tx_name_en' => 'Veron nimi (EN):',
		'static_taxes_item.tx_code' => 'Verokoodi:',
		'static_taxes_item.tx_scope' => 'Peruste:',
		'static_taxes_item.tx_scope.I.0' => 'Maa',
		'static_taxes_item.tx_scope.I.1' => 'Osavaltio/provinssi',
		'static_taxes_item.tx_class' => 'Luokka:',
		'static_taxes_item.tx_class.I.0' => 'Verolliset tuotteet',
		'static_taxes_item.tx_class.I.1' => 'Verolliset palvelut',
		'static_taxes_item.tx_class.I.2' => 'Verolliset tuotteet ja plavelut',
		'static_taxes_item.tx_rate' => 'Yksikköhinta:',
		'static_taxes_item.tx_priority' => 'Etuoikeus:',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
		'static_countries_item.cn_iso_2' => 'Codul ISO 3166-1 A2 al tarii:',
		'static_countries_item.cn_iso_3' => 'Codul ISO 3166-1 A3 al tarii:',
		'static_countries_item.cn_iso_nr' => 'Codul ISO 3166-1 Nr al tarii:',
		'static_countries_item.cn_currency_iso_nr' => 'Numarul ISO 4217 Nr al valutei:',
		'static_countries_item.cn_currency_iso_3' => 'Codul ISO 4217 A3 al valutei:',
		'static_country_zones_item.zn_country_iso_nr' => 'Codul ISO al tarii:',
		'static_country_zones_item.zn_country_iso_2' => 'Codul ISO 2 al tarii:',
		'static_country_zones_item.zn_country_iso_3' => 'Codul ISO 3 al tarii:',
		'static_country_zones_item.zn_code' => 'Codul zonei:',
		'static_languages_item.lg_iso_2' => 'Codul ISO 2 al limbii:',
		'static_currencies_item.cu_iso_3' => 'Codul ISO 3 al valutei:',
		'static_currencies_item.cu_iso_nr' => 'Numarul ISO al valutei:',
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>